### ISSUE TITLE
No icons in buttons

### ISSUE THREAD

**Issue by tornel** [FrancescoCeruti/linux-show-player#1]
Hi Francesco:

I've just installed the new version of the program a few minutes ago. It's looking great!. However in the List Layout I've got no icons on some of the buttons.

I'm attaching a screenshot demonstrating it. If you need more info just say so.

Installed from .deb provided. Ubuntu 14.10 (clean install)

![screenshot from 2015-04-05 17 56 18](https://cloud.githubusercontent.com/assets/5472468/6998967/058bf400-dbc2-11e4-94c3-b4a254563f15.png)

**Comment by FrancescoCeruti** [comment]
Hi,
the problem should be solved in the 0.3-1 release, try to install it (remove the old and install), let me know (or close the issue) if works correctly.

Thanks for the report!

**Comment by tornel** [comment]
Thanks! I'll let you know tonight

**Comment by tornel** [comment]
Yes! it's fixed now!
