### ISSUE TITLE
Install troubles on Debian

### ISSUE THREAD

**Issue by fmiser** [FrancescoCeruti/linux-show-player#100]
I'm wanting to run LiSP from a laptop with Debian8 installed.  It does not have a 64 bit processor. In looking at the release page, I see that Debian Jessie (8) has trouble with 0.4.1, so I tried the next earliest version, 0.4fix1

I tried using the .deb packages:
> sudo dpkg -i linux-show-player_0.4fix1-1_all.deb python3-jackclient_0.4.1-1_all.deb python3-mido_1.1.14-1_all.deb python3-sortedcontainers_1.4.4-1_all.deb 

It complained that it could not find python3-all, which seems to not be in the repository.  And python3-rtmidi, which is not in the repository but is on the release page - but only 64 bit.  So if I use that and get it running on the desktop - it **will** fail on the laptop because it is 32 bit.

I found mention of installing that from pip.  That appears to be successful - but aptitude doesn't know about it, so the .deb install still fails.

So I tried pip again, hoping that with all the .deb other bits it would now work.
> pip3 install linux-show-player-0.4-fix1.zip

That failed and reported:
> Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-peo1ernz-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-csi5c1np-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-peo1ernz-build

At this point, I still haven't ever seen it run!  So, although I have a metered internet connection, I downloaded rather large the static built appimage - just to see if LiSP would work for my projects.

I added execute permission and ran it.
> ./Linux_Show_Player-v0.5-1-x86_64.AppImage

And that failed to stay running.  I got two dialog boxes.  First on asking:
> Would you like to integrate ./Linux_Show_Player-v0.5-1-x86_64.AppImage with your system?

I answered no.  Then
> Should this question be permanently disabled for LinuxShowPlayer?

I answered no.

I got my prompt back after seeing the error:
> This application failed to start because it could not find or load the Qt platform plugin "xcb"

Details are documented in  #97. 

But even if I get it running on my 64bit desktop with the appimage, I'm still stuck getting it to run on my 32 bit laptop.

Though I don't write "real" code (lots of bash scripts), I have many years working with getting programs compiled with gcc.  But the limited documentation and quite unfamiliar to me process really has me stumped.

**Comment by fralix** [comment]
Hey, may be you try copying the git repository (`git clone https://github.com/FrancescoCeruti/linux-show-player.git`) and then run it from there? 
You should also be able create an AppImage with the Recipe located in `./dist/AppImage/`

If this doesn't solve your problem I will try reproducing the problem on my old laptop with the reported conditions and if that fails as well it is a problem for the main dev 😄 

> 
> I added execute permission and ran it.
> 
>    >./Linux_Show_Player-v0.5-1-x86_64.AppImage
> 
> And that failed to stay running. I got two dialog boxes. First on asking:

Just to that: Did you try to run the 64bit version on your 32bit machine?

**Comment by FrancescoCeruti** [comment]
@fmiser you should be able install/build the 0.5 on Debian 8, but I'll test it when at home, the AppImage on the release page has been build on Ubuntu 16.04 to solve a few problems with outdated libraries, as a result it doesn't work on Debian 8, my bad, I'll see what can be done.

About your second (`pip3`) attempt, the error is very strange, my suggestion is to remove the .deb packages installed from the release page, then try with last version, following the [wiki](https://github.com/FrancescoCeruti/linux-show-player/wiki/Install#manual-installation)

Since I'm planning a small 0.5.1 release I'll try to see if I can improve the situation, providing ubuntu/debian packaging, using some building platform.

**Comment by FrancescoCeruti** [comment]
So, Linux Show Player is being packaged for the Debian "buster", I'm thinking to provide a (back-ported) version for Debian 9, maybe Ubuntu 16.04  (and 18.04 when out).

**Comment by FrancescoCeruti** [comment]
For the 0.5.1 deb packages are now provided, for debian stretch (64bit and 32bit).
