### ISSUE TITLE
Namespace Gst not available

### ISSUE THREAD

**Issue by adaptiman** [FrancescoCeruti/linux-show-player#102]
When executing linux-show-player on raspbian desktop (Debian Stretch 2017-11-16, kernel version 4.9), I get an error:

`libEGL warning: DRI2: failed to authenticate
...
ValueError: Namespace Gst not available`

I've attached a full output file.
[output.txt](https://github.com/FrancescoCeruti/linux-show-player/files/1772903/output.txt)

#### Expected Behavior
As the dependencies appear to be satisfied, I would expect the application to execute.

#### Actual Behavior
The error is thrown.

#### Step to reproduce
This error is reproducible. I have started with a clean current image of Debian Stretch, cloned the repo, and used pip3 to generate the application. The installation is successful. the error happens when the program is executed.

**Comment by FrancescoCeruti** [comment]
Hi, have you installed all the packages listed in the wiki page?

**Comment by adaptiman** [comment]
all python packages present except scandir (my python3 version is 3.5.3). There is no package for raspbian called build-essentials. There IS a package (installed) called build-essential (12.3). is this what you're looking for? There is also no package called asound2.  Is there a substitute? Attached is an output of all my module versions.
[investigation.txt](https://github.com/FrancescoCeruti/linux-show-player/files/1775164/investigation.txt)

**Comment by adaptiman** [comment]
UPDATE: Looks like my version of gstreamer is 1.10 when 1.0 is expected. I'm guessing on this.

**Comment by FrancescoCeruti** [comment]
sorry I didn't have the time to check the problem, the GStreamer version is not a problem, it's only checking for major versions. I suspect I've missed a few packages in the wiki, I'm going to verify it as soon as possible

**Comment by adaptiman** [comment]
Thanks! I'm using your software to create a raspbian podcasting station. I've forked the code and may be able to contribute some interesting features once I get my station completed. I'm using the [PiSound](https://blokas.io/) board to create hi-fi inputs and outputs. There is also a MIDI connector as well, so I may try that.

**Comment by FrancescoCeruti** [comment]
Great! So I think it's probably some gobject-introspection package, this should do the job `gir1.2-gstreamer-1.0`, `gir1.2-gst-plugins-base-1.0` and `gir1.2-gst-plugins-bad-1.0`.

Let me know, so I can update the wiki page :)

**Comment by adaptiman** [comment]
Installed gir1.2 which installed more dependencies than I care to list here, but included all those you've listed. The launch works, but throws the following warning:

`libEGL warning: DRI2: failed to authenticate
14:21:11.706 WARNING:: Cannot load module: timecode`

This is a mere annoyance as the application does launch. I will do some more testing and let you know the results. Thanks for the help!

**Comment by FrancescoCeruti** [comment]
Okay, good, I've also uploaded two .deb packages for debian stretch, in the release page, if you want.

The warning is related to the timecode plugin, you can try to use the `--log debug` to see more info, but I think it related to the `ola` package.
