### ISSUE TITLE
[suggestion] embedding the PDF manual

### ISSUE THREAD

**Issue by trebmuh** [FrancescoCeruti/linux-show-player#104]
I'd suggest to embed [the PDF manual](https://github.com/FrancescoCeruti/linux-show-player/releases/download/v0.5.1/LinuxShowPlayer_UserDocs.pdf) into a resources/ folder (or something like that) directly within the sources.

Not a big deal if there is a reason for that not to be done, but it could help a little when packaging.

**Comment by FrancescoCeruti** [comment]
If you want to avoid sourcing it from the release page, you can build it from the docs/user folder.

**Comment by trebmuh** [comment]
Good suggestion @FrancescoCeruti . That's what I've done now.

Closing now. Thanks you!
