### ISSUE TITLE
Launch Session from Command Line

### ISSUE THREAD

**Issue by adaptiman** [FrancescoCeruti/linux-show-player#105]
This is a feature request. It would be nice to be able to load a session file from the command line so the program could be executed on startup of the host machine. In addition, it would be extra-special nice to be able set a flag at the command line to indicate whether or not to launch in full screen.

If you don't have time to do this, give me an indication on the best place to implement this and I'll work on it.

**Comment by FrancescoCeruti** [comment]
Hi, you can already load a session from the command line using the `-f` option. I can also add one for the fullscreen :+1:
