### ISSUE TITLE
PiSound Card Problem

### ISSUE THREAD

**Issue by adaptiman** [FrancescoCeruti/linux-show-player#106]
I just installed a pisound (https://blokas.io/) card. Sounds launched from linux-show-player do not play through the new card, but are played through the standard pi sound output. Audacity defaults to the new card and works correctly. I suspect that linux-show-player is not set to use the new soundcard. Is there a way to configure that?

**Comment by FrancescoCeruti** [comment]
Hi, by default LiSP use a GStreamer plugin which "auto-detect" the default output device. You may try using directly the alsa-sink se [here](http://linux-show-player-users.readthedocs.io/en/latest/gst_media_settings.html).

Also, check if `gstreamer1.0-alsa` is installed, that might be the problem

**Comment by adaptiman** [comment]
gstreamer1.0-alsa is present. I've tried all of the various "sinks" with no luck. Is there a way to tell what card ALSA uses?

**Comment by FrancescoCeruti** [comment]
In the alsa sink you can select the sound device to use

**Comment by adaptiman** [comment]
The new soundcard is not in the list of ALSA Out devices. There are three choices:
default
bcm2835 ALSA
PS-3AEHTBB snd-soc-dummy-dai-0

None of these work. Is there a way to make the installation "re-read" the list of soundcards?

**Comment by FrancescoCeruti** [comment]
It's probably the last one, the settings dialog read the sound devices every time, when I've more time I'll investigate

**Comment by FrancescoCeruti** [comment]
So, first, I'm assuming you are using ALSA alone. You don't have pulseaudio or jack running, right?

Try to `cat /proc/asound/pcm` to see if all the device in this file are listed in LiSP

**Comment by FrancescoCeruti** [comment]
For ALSA you can find information here:
- https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture
- https://wiki.debian.org/ALSA

**Comment by adaptiman** [comment]
PS-3AEHTBB snd-soc-dummy-dai-0 is the new soundcard. Specifying this card in the pipeline results in three different results:
1. First time, the meters are "jumping" but not sound is generated.
2. Second time, the above mentioned error is generated.
3. Third time and all subsequent plays, the green light is on the media button but the timer doesn't decrease nor any sound generated, not any meter action.

Very strange. BTW - Audacity automatically handles the new soundcard without any modifications.

**Comment by FrancescoCeruti** [comment]
Mmh, `3` is a LiSP bug I'm aware of, it happen when a media-cue have problems with GStreamer.
The suspicious thing is that it "run" on the first, but then fail :thinking:

Have you tried loading a session with cue already configured for with the correct alsa device? Also you can change the default sink (new cue will be created using that) in `File > Preferences > GStreamer`

If nothing change, try running with this `GST_DEBUG=2,audiosink:5 linux-show-player -l debug` and post the output.

**Comment by adaptiman** [comment]
> Have you tried loading a session with cue already configured with the correct alsa device? Also you can change the default sink (new cue will be created using that) in File > Preferences > GStreamer

Yes. I've changed the default sink to ALSA, changed media cue ALSA Out to the new soundcard. I get the exact three results earlier noted.

I will run the debug command you've specified and post the result.

**Comment by FrancescoCeruti** [comment]
mmh, still unclear, to be honest I'm no alsa expert, probably I'm missing something ... :disappointed: 

Have you tried to set the soundcard as default and use the "Auto Sink" (or the "default" device) in LiSP?
Also have you considered using pulseaudio or Jack?

**Comment by FrancescoCeruti** [comment]
Continued in #107
