### ISSUE TITLE
PiSound Card Information

### ISSUE THREAD

**Issue by adaptiman** [FrancescoCeruti/linux-show-player#107]
_continuation of #106_

I started a new issue because I think that's what you asked me to do in the last thread. If this is incorrect, please let me know.

I figured out at least one problem. In the ALSA system, software mixing (i.e., the ability to play more than one file at once) is not automatically enabled. I was able to get it to work by adding the following code in ~/asoundrc:

```
pcm.!default {
	type plug
	slave.pcm "dmixer"
}

pcm.dmixer  {
 	type dmix
 	ipc_key 1024
 	slave {
		pcm "hw:1,0"
		period_time 0
		period_size 1024
		buffer_size 4096
		rate 44100
	}
	bindings {
		0 0
		1 1
	}
}

ctl.dmixer {
	type hw
	card 1
}
```

Note card 1 in the dmixer block - PiSound installs as card 1.

This code enables software mixing using the ALSA dmix plugin. By doing this, my files play in the application, but when they stop, I get an error:

```
gst-resource-error-quark: Could not open audio device for playback. Device is being used by another application (4)
gstalsasink.c(858): gst_alsasink_open(): '/GstPipeline:pipeline2/GstAlsaSink:sink:Device'hw:01,00' is busy
```

**Comment by adaptiman** [comment]
I think I got it to work. I set the default GStreamer Settings to ALSA Out, and leave the object ALSA Out device set to default. This fires the audio files as expected.

**Comment by FrancescoCeruti** [comment]
I meant a new comment under the same issue (instead of editing a previous comment), but don't worry.

> I figured out at least one problem. In the ALSA system, software mixing (i.e., the ability to play more than one file at once) is not automatically enabled.

Didn't thought about that possibility ... glad you find out the source of the problem.

> I think I got it to work. I set the default GStreamer Settings to ALSA Out, and leave the object ALSA Out device set to default. This fires the audio files as expected.

:+1: ... probably when you set the specific card you don't go through the mixer
