### ISSUE TITLE
Add "Unselect" action to right click menu when the cue is already selected

### ISSUE THREAD

**Issue by nodiscc** [FrancescoCeruti/linux-show-player#11]
Hi, could the preferences dialog allow creating all future Media cues with `Pause instead of stop` enabled? It may be faster than the default workflow (edit pause/stop settings invidually in each cue) if you have a pause-only cart.

**Comment by FrancescoCeruti** [comment]
You should be able to achieve the same result if you select all the cue (`Edit` menu or `[Ctrl+A]`) and  than use the multi-editing dialog (`Edit` menu or `[Ctrl+Shift+E]`).

**Comment by nodiscc** [comment]
Thanks! https://github.com/FrancescoCeruti/linux-show-player/wiki#editing-multiple-cues

Is there a way to select _some_ cues (not all cues with CTRL+A) ?

**Comment by FrancescoCeruti** [comment]
Yeah, it should be: `Right click on the cue > select`

**Comment by nodiscc** [comment]
Thx again, I have updated the wiki. As far as I can see, there's no option to Unselect a cue (Except `Edit > select none`). Can you change the right click menu so that when a cue is already selected, the menu entry turns to `Unselect`?

**Comment by FrancescoCeruti** [comment]
If you use the `select` action again the cue is deselected.
Unfortunately the current context-menu implementation is not able to access the selection-state of a cue.
For now I'll try to find a workaround to do this, in the future I'm going to implement a more flexible solution.

**Comment by nodiscc** [comment]
> If you use the select action again the cue is deselected.

This is ok, I didn't try to re-click select. I've added it to the doc, so not a big deal if it stays as it is. Just something to know.

**Comment by FrancescoCeruti** [comment]
Ummh, well I've noticed that actually the cue is not deselected, with the next commit this will be fixed.
Anyway, I forgot to mention `Ctrl+Click` select/deselect the cue (Added to the wiki)
