### ISSUE TITLE
Command Cue : post wait not working

### ISSUE THREAD

**Issue by aroomthedoomed** [FrancescoCeruti/linux-show-player#111]
In a Command Cue, if you set **post wait** to 3 seconds and **auto-follow**, the 3 seconds are not being considered and the next cue will fire instantly. the 3 seconds are not being displayed in the post wait column as well.

**Expected Behavior**

wait 3 seconds and fire next cue (auto-follow)

**Actual Behavior**

fire next cue instantly, like an auto-next

**Step to reproduce**

1. Create a command cue
2. Double clic on it to edit
3. Go to Cue > Pre/Post Wait
4. Add 3 sec to post wait and select auto-follow
5. Fire cue

**Comment by FrancescoCeruti** [comment]
As stated in the docs (http://linux-show-player-users.readthedocs.io/en/latest/cues.html#pre-post-wait):

> Auto Follow: When the cue end, execute the next cue (Post wait value is ignored)

You should use `auto-next`

**Comment by aroomthedoomed** [comment]
damn me  : facepalm :

thanks

**Comment by FrancescoCeruti** [comment]
> what was the logic behind this choice?

Behind the naming? Honestly I don't remember, but `auto-next` probably can be changed in something better, maybe `auto-continue`, or `after-cue` and `after-wait`, any idea?

**Comment by FrancescoCeruti** [comment]
The options have been renamed for better understanding (coming in 0.6 version)
