### ISSUE TITLE
MTC timecode output for syncing external systems

### ISSUE THREAD

**Issue by AlCan13** [FrancescoCeruti/linux-show-player#112]
First of, LiSP is very cool, long waited for application. Thank you!

the problem I am facing:
I am using Martin M-PC and wanted to sync audio and lighting cues. But LiSP only offers ArtNet timecode out. So I have searched for solution to close the gap, but there is nothing - free or paid.

Also it appears that most of the Lighting consoles understand MTC  (MIDI Timecode), not ArtNet timecode.

Thus I am suggesting to implement new feature -  MTC  (MIDI Timecode) output similar to how you do ArtNet Timecode output.

cheers,

**Comment by FrancescoCeruti** [comment]
Hi @AlCan13, MIDI Timecode is already implemented in the development version (see #56), I'm trying to put as much time as I can into it to have a 0.6 version asap :)

**Comment by AlCan13** [comment]
Hi, @FrancescoCeruti if you need any help with testing, let me know.
I do not have any midi timecode h/w, though. Just another user with bunch of computers.

**Comment by AlCan13** [comment]
Hi @FrancescoCeruti 
I just had a deep dive into Martin M-PC sync to MIDI timecode. Things are not as trivial as they appear.

Thus, I have a question:
using definitions here http://tweakheadz.com/sync-mmc-mtc-smpte/,  what exactly will be implemented in LiSP.

M-PC was picky enough not to recognize clock from Mixxx DJ s/w but worked OK with Reaper DAW.
Also M-PC didn't like anything I generated in MIDI-OX.

cheers,

**Comment by FrancescoCeruti** [comment]
Hi,
the timecode plugin is able to send MIDI TimeCode (MTC) in 3 formats SMPTE, FILM, EBU, where the difference is in the number of frames per second.

Keep in mind that the plugin has been written by @offtools, I'm not very familiar with this protocols
