### ISSUE TITLE
Several issues in LiSP interface

### ISSUE THREAD

**Issue by egallyamov** [FrancescoCeruti/linux-show-player#113]
I am using LSP for a theater show play and I've found the following issues:
1. Any FadeOut action cue (whether Pause or Stop) doesn't fade out sound, but abruptly stops it. In order for me to make the Pause or Stop, triggered by the action cue, actually fading out, I need to edit the Media Cue options (Fade In/Out). However, that makes this setting global for this cue, and if I, the next time, I want to stop/start it abruptly, it still will fade in/out.
2. Lack of keyboard shortcuts for the global actions (stop, play, fade in/out) is a big miss. Having it would benefit me a lot!
3. Not having option to copy/paste existing cues with already set properties is a huge miss.
4. When 2 or more tracks are started simultaneously and one of them is not started from the beginning, Pause/FadeOutPause action applied on both of them makes this track start not from the paused position but from the initial time.

**Comment by egallyamov** [comment]
Hello,

Thanks for your reply. 
Regarding the first question, I was using the Collection Cues instead of Index Action. Indeed using Index allows what I was aiming for. 
Regarding the 3rd point, is there also a shortcut for deleting cue action?

Thanks again for your dedication!

**Comment by FrancescoCeruti** [comment]
Sorry for the late reply.
Right now there isn't any shortcut for deletion, it's already been requested [here](https://github.com/FrancescoCeruti/linux-show-player/issues/110#issuecomment-380734247)
