### ISSUE TITLE
Enhancement/Request - Global keybinding for Stop-All event

### ISSUE THREAD

**Issue by MarcAngelo** [FrancescoCeruti/linux-show-player#114]
I like LiSP very much, and would like to request the option for a generic keybinding to perform "Stop-All", just like how "space" works as default to start a cue, it would be convenient to have a similair keybinding for stopping al current playing cues.

When (I use list view) a media cue is selected, it can be started with hitting "space".
It would also be nice to have a default keybinding, to be able to stop all playing cues at once.
(a generic STOP button sort of speak). I would prefer to be able to use the ESC button (or TAB) for that.

Now, the only option is to use the mouse and click on the STOP button in the top right corner, or add a "Stop" keyboard shortcut for Cue control to the specific media cue, but then ESC, TAB etc. are not useable.

I did read the manual, but was unable to find if this could be configured in the config-file.

**Comment by FrancescoCeruti** [comment]
Hi,
I'm already considering to add this, and other shortcuts, with a common interface to configure them

**Comment by musger** [comment]
Yes, at least a global stop-all key would be nice (and would save the extra work adding a stop shortcut to every cue). Is it correct that non-printing keys like ENTER, ESC, and the like don't (Yet) work in 0.5.1? Thanks!

**Comment by FrancescoCeruti** [comment]
Hi! This has already been addressed in the development version, it will be available with the 0.6 version or you can try it now using the "experimental" version ([see here](https://www.linux-show-player.org/download.html))
