### ISSUE TITLE
Info-panel size

### ISSUE THREAD

**Issue by InTheMorning** [FrancescoCeruti/linux-show-player#116]
Not sure if this enhancement request would fall under the 'composable UI' mentioned in the TODO, but there are 2 suggestions that would be precious to me:

1)  Ability to lock the cue order in list mode.  (to prevent accidentally re-ordering cues with the mouse/touchpad)

2)  Ability to resize the 'cue description' vs 'cue list' frames — to be able to see more info about the upcoming cue, (such as dialogue / actor actions preceding the cue) without having to scroll through it, while sacrificing space for the list (since showing passed cues and more than a few upcoming cues is not necessary)

Ideally, both of these suggestions could be combined into a visual mode/preset (show mode) with larger description to cuelist ratio and locked list — still allowing to toggle back to the current list layout (edit mode) for easy session configuration.

**Comment by FrancescoCeruti** [comment]
Hi,
I can easily provide two option for info-panel size and to lock the cue, ideally the second will be accessible from the layout menu, while the panel size one only from the app settings.
