### ISSUE TITLE
Bug with wav file at a modified speed.

### ISSUE THREAD

**Issue by LoakAudio** [FrancescoCeruti/linux-show-player#117]
Hello Francesco and _Bravo_ for this soft I'm using everyday in a Theater (I'm the sound manager).
I'm under Debian Stable, last update, using the last AppImage of your software.
I've found the following bug : Build a cue with a wav file and set its speed at 0,9. The first time it is read it's OK, the second time LiSP close suddenly with "Segmentation fault".
Note that my /tmp folder is mounted in RAM.
Tell me if other informations are needed .
And Thank you for this nice job I'm following closely.

Edited : after some research, the bug also appears if /tmp is on the hard drive.
It does not happen with Debian testing into a Virtualbox (LiSP from the repository).

**Comment by LoakAudio** [comment]
Thank you for your fast answer,
I've joined the debug log file. I hope it'll help.
I've tried with FLAC but same, I will try other formats and will tell if something work.

[LiSP debug log.txt](https://github.com/FrancescoCeruti/linux-show-player/files/2076161/LiSP.debug.log.txt)

**Comment by FrancescoCeruti** [comment]
> The first time it is read it's OK, the second time LiSP close suddenly with "Segmentation fault".

mmmh, you mean when you open the edit dialog? or when you start the playback? :thinking:

**Comment by LoakAudio** [comment]
It happened when I start the playback for the second time. First read of the file it's ok, second read LiSP close itself.
I've started LiSP with the `--log debug` parameter, activated speed in the _bitoduc_ menu of a file, read it two times, LiSP closed itself on the second time and copy the logs in the terminal.

**Comment by LoakAudio** [comment]
OK, I will test the .deb this week end.
At first I've tried with the .deb but some dependences were missing. As the Appimage was working I've not investigate anymore (lazy guy ...). I will this time.
Thank you, now stop talking and go to code :)
