### ISSUE TITLE
GO button via MIDI

### ISSUE THREAD

**Issue by ciacnorris** [FrancescoCeruti/linux-show-player#118]
Hello! Is it possible to activate the GO button via MIDI? Using the keyboard is a problem for me.
If it is not, then take this as a feature request :)

**Comment by FrancescoCeruti** [comment]
Hi, it's not yet supported, but you may look at #80 if you really need it :)

Closing as duplicate of #58

**Comment by aroomthedoomed** [comment]
so far, I've been using this script to map midi notes from my controller - Korg nanoKontrol 2 - to keys, to control LiSP during a show.

`#!/bin/bash
aseqdump -p "nanoKONTROL2" | \
while IFS=" ," read src ev1 ev2 ch label1 data1 label2 data2 rest; do
    case "$ev1 $ev2 $data1" in
        "Note on 41" ) xdotool key space ;;
	"Note on 43" ) xdotool key Up ;;
	"Note on 44" ) xdotool key Down ;;
    esac
done
`

**Comment by mattotone** [comment]
Thanks for the Script, i too needed this functionality and came across your script after trying to create my own python script.
