### ISSUE TITLE
Volume Control action cue: fade time doesn't show in dialog if under one second

### ISSUE THREAD

**Issue by claytonpeters** [FrancescoCeruti/linux-show-player#12]
If I create a Volume Control action cue and set the fade time to be less than a second and then click OK, then the fade time is saved (it appears as such in the Action column in the cue list), but when re-opening the properties for the cue, the Fade time reverts to zero, which is then saved the next time you click OK.

**Comment by FrancescoCeruti** [comment]
Thanks for the report :)
