### ISSUE TITLE
Unexpected behaviour when editing Index Action cues 

### ISSUE THREAD

**Issue by keithjnewman** [FrancescoCeruti/linux-show-player#128]
When  editing an Index Action cue the action on the 'Action Settings' always reverts to Start. 
It is not possible to change it from Start without first changing the Target index setting up or down. If you don't actually want to change the target it works if you increase or decrease the target and then set it back.

#### Unexpected behaviour 

On editing an Index Action cue, the Action is always set to Start and cannot be changed without first changing the Target index.

#### Expected behaviour

On editing an Index Action cue, the Action is set to whatever you last set it to (Start is as good a default as any on a new cue) and can be changed without having to change the target index.

#### Steps to reproduce behaviour

1. Add a Media cue that plays an mp3.
2. Add a Index Action cue.
3. Edit the Index Action cue you have just created.
    a. On editing the cue you will see; Use a relative index set, Target index 0 and Action Start.
    b. Change the target to point to the Media cue added at step 1.
    c. Change the Action to FadeOutPause.
    d. Click Apply.
    e. Click OK.
4. Click Go on the Media cue and then Go on the Index Action cue to prove that they work as expected.
5. Edit the Index Action cue.
    a. On editing the cue you will observe that the Target is what you set but the Action has reverted to Start
6. Click Cancel
7. Click Go on the Media cue and then Go on the Index Action cue to prove that they work as they did before.
8. Edit the Index Action cue.
    a. On editing the cue you will observe that the Target is what you set but the Action has reverted to Start
9. Try altering the action, you will find that you can't.
10. Click OK
11. Click Go on the Media cue and then Go on the Index Action cue. You will see that it appears to do nothing.
12. Stop the media file from playing.
13. Click Go on the Index Action cue. You will find that it now starts the media cue.
14. Edit the Index Action cue.
    a. On editing the cue you will observe that the Target is what you set but the Action has reverted to Start
15. Try altering the action, you will find that you can't.
16. Increase the target by 1.
17. Decrease the target by 1.
18. Try altering the action, yo will now find that you can.
19. Change the action and test. It should work as expected.

#### Environment in which this behaviour has been observed.

Ubuntu 16.04 64 bit
LiSP 0.5.1 from AppImage

**Comment by FrancescoCeruti** [comment]
Hi, and sorry for the delay,
I'm aware of the problem, in fact is already been fixed for the version.

Thank for reporting it anyway :-)
