### ISSUE TITLE
My impressions and suggestions after testing this in a real show 

### ISSUE THREAD

**Issue by minecraft2048** [FrancescoCeruti/linux-show-player#13]
So, because my cohort decided to do a stage play for some sort of school work, I was picked as the sound effects coordinator. The school always use Reason with a MIDI keyboard to play the sound effects, but because I'm in Linux, after some googling time, I found this and I immediately saw a much better solution than to abuse a DAW sampler to play sound effects and background music that holds the sound card exclusively so that other applications cannot use it. And yes, our play was successful, so thank you :+1: :)  

So here is what I think what this project needs:

1.  Documentation! Although the interface is familiar to me because I understand computers, not everyone understands computers and they need manual on how to use this thing. Even I don't understand some part of the program, like some cue thingy

2. Make the program ignore MIDI note on velocity value, as there is nothing more frustrating than to set up the keyboard control by the learning feature and then it mysteriously fail to work because you are pressing the keyboard harder

3. An option to choose either press to start and press to stop, or hold the key to play the sound 

4. Some sort of mixer so that this program can simultaneously play background music and sound effects while be able to change the volume on the fly. Currently I use Non Mixer and Linux Show Player JACK multiple channel output, but assigning the channels to each sound effects and background music is very tedious, and this leads me to the next point:

5. Group edit, so basically you can shift-select the effects and change some of its parameters, like GStreamer setting, or make a group and assign the same sound settings (not MIDI keybindings) to any effects inside the group

6. Windows compatibility, so that our school can stop abusing that poor DAW... 

The thing is that I have some Python experience, but I think that I'm not skilled enough to work on this yet, but I'll try. Unfortunately, the last time I uninstall the .deb version and try to install it manually, I accidentally created some sort of dependency hell that make this Xubuntu unable to run Linux Show Player anymore, so I'd installed Ubuntu Studio in other partition

**Comment by nodiscc** [comment]
Hi @minecraft2048 I also plan to run l-s-p in production in the near future (permanent installation at venue), thanks for the report, and I will do a report after my first try.

I can help with:

`1.` Doc: I've started something at https://github.com/FrancescoCeruti/linux-show-player/wiki, your help is welcome (page is world-editable). We can use https://ipfs.pics/ for image storage (image storage on GH wikis is tricky). We can both work on the wiki and subscribe to https://github.com/FrancescoCeruti/linux-show-player/wiki.atom for recent changes

`2.` and `3.` good catch. I think separate issues need to be reported.

`4.`  was reported at https://github.com/FrancescoCeruti/linux-show-player/issues/10

`5.` multiple selection: can be done, check https://github.com/FrancescoCeruti/linux-show-player/wiki#selectingediting-multiple-cues

`6.` **linux**-show-player :D but more seriously I think there are already good tools for this job on windows (Live, many samplers...), and a port is a serious amount of work for the (only) developer. It may be a good time to setup a Linux workstation? Check https://github.com/nodiscc/awesome-linuxaudio/ for software and help links (currently working on the setup part, but you can have a look at one of the premade distributions)

**Comment by FrancescoCeruti** [comment]
Hi @minecraft2048  and thank @nodiscc ;)

`2. & 3.` are implemented in the development version, the MIDI velocity is ignored and for both MIDI and keyboard you can add multiple entry and set a specific action.

![schermata da 2016-03-26 00-35-43](https://cloud.githubusercontent.com/assets/5596673/14056328/c4e69b08-f2ea-11e5-8673-c16a51af7a50.png)

`4.` afaik a real application mixer cannot be done as currently every "media-cue" use it's own independent output to the system, so, for now, your solution is probably the best.

`6.` not-linux support is a looong term todo, it shouldn't be too hard, but my experience in other platform is currently near 0.

**Comment by nodiscc** [comment]
> Some sort of mixer so that this program can simultaneously play background music and sound effects while be able to change the volume on the fly. Currently I use Non Mixer and Linux Show Player JACK multiple channel output, but assigning the channels to each sound effects and background music is very tedious, and this leads me to the next point:

@minecraft2048 Have you tried saving a template session in non-session or similar JACK session manager (ladi...) with your full LiSP/routign settings to save some precious setup time? If so, can you share your session settings or jack I/O diagram screenshot? I'd like to work on some show templates that could be added to the doc (https://github.com/FrancescoCeruti/linux-show-player/issues/15).

I will close this issue, it's mostly fixed (except win support, if you'd like to reopen another issue for this specifically) or has been documented. Feel free to reopen.

**Comment by minecraft2048** [comment]
Noted, I've used Claudia for session management, and it work great, but it is in my other laptop right now
