### ISSUE TITLE
Speed pipeline setting isn't obeyed when cue is looped.

### ISSUE THREAD

**Issue by ammonriley** [FrancescoCeruti/linux-show-player#136]
Add audio cue, and set Repetitions to -1 in "Media-Cue" tab, so it loops forever.  Add Speed to the pipeline in the Media Settings tab, and change the speed enough to be noticeable.  Play the cue.  The first time the cue is played, the speed setting is obeyed, but on every subsequent repetition, the speed setting is ignored, and the cue is played at normal speed.

I'm using the AppImage, v0.5.1.

**Comment by ammonriley** [comment]
It was, indeed, a wave file that I was using.  I'll try other files once I'm back home.

**Comment by FrancescoCeruti** [comment]
I'm trying to figure out how to solve it. For reference, here the bug opened on the GStreamer tracker: https://bugzilla.gnome.org/show_bug.cgi?id=797313
