### ISSUE TITLE
Drag & Drop to add new media cues

### ISSUE THREAD

**Issue by mitscherdinger** [FrancescoCeruti/linux-show-player#137]
Hi, there!

Using mate under Debian Testing, I just can't choose some audio files from the file manager and drop them into LSP. Could be a mate issue, but I thought I just keep you informed (in case it is not a mate issue).

**Comment by ghassenghouibi** [comment]
Hello @FrancescoCeruti ,
Is this issue have been resolved ?
I tried to drag and drop audio file on the develop branch  but it doesn't work.I checked the files and i saw there is something to do (line commented #todo). So  i would like to work on this part but i don't know if it's already done.
Thank you

**Comment by FrancescoCeruti** [comment]
Hi, it's not yet implemented, and I'm not working on it :smile:
