### ISSUE TITLE
LSP refuses to recognize files with upper case suffix as valid audio files

### ISSUE THREAD

**Issue by mitscherdinger** [FrancescoCeruti/linux-show-player#138]
I know, it's not common for linux to use upper case endings at all, but sometimes some stupid people or apps just don't care and write f.e. *.MP3 instead of *mp3. This was the case in my latest project where I wanted to import that miswritten item. It was not listed as a valid audio file to import, so I had to to take the workaround and rename that file. Guess, it's no big deal to make LSP read that stuff. Would be cool, although we all know, that upper case suffixes shouldn't exist…

**Comment by FrancescoCeruti** [comment]
I'm aware of the problem, it's actually a problem between Qt and the GTK file-chooser dialog, (see https://gitlab.gnome.org/GNOME/gtk/issues/1347).

I'll see if I can find some reasonable solution
