### ISSUE TITLE
LSP cuts beginning of audio cue if using jack output

### ISSUE THREAD

**Issue by mitscherdinger** [FrancescoCeruti/linux-show-player#139]
Hi, there!
In my latest project I used LSP with jack and it catched my ear that the first miliseconds of the cue got lost due to the time gstreamer needed to connect. This is one of the few design decisions where ShowQ does better as LSP: Besides the fact that LSP is much more flexible regarding output connections - which of course is great - ShowQ uses a persistent connection to the jack output and that guarantees a more or less latency- and lossless execution of all the cues. I wonder if it was possible to give LSP a persistent output to jack connections, too…?
OR, if this comes across your conception of LSP, let the user choose between lossless and delayed playback and let LSP connect immediately, no matter if there is a delay (of a few ms) added in the cue preferences or not. The status quo today is that it will be connected to jack AFTER the delay.
If this all seems to be too difficult to make everyone happy, I wouldn't mind getting a jack-only-option, which would be really close to the ShowQ model.

**Comment by FrancescoCeruti** [comment]
Mmh, looks strange, can you check it's not something like [this](https://github.com/FrancescoCeruti/linux-show-player/issues/131#issuecomment-415087495)?

> I wonder if it was possible to give LSP a persistent output to jack connections, too…?

The default GStreamer implementation spawn new connections every time a media is started.
I cannot change this directly, but it's likely that in future versions the behavior of the backend will prevent this (by keeping the underlying media paused instead of stopping it).

**Comment by mitscherdinger** [comment]
Thinking about it, again, I guess, persistent connections would break the "connection per cue" feature. So, that would be no good idea.
I guess, it's indeed just the 20 - 30 ms that are missing. On most cues, you won't even notice. But there are tracks with high bpm, where the first beat seems to be left out.
If you're already working on or at least are aware of it, nevermind my report.

**Comment by mitscherdinger** [comment]
A closer look at my "problem" shows, that it's just not sustainable, to blame LSP cutting a beginning of a cue. I guess, in my latest job I got some cues misconfigured. Maybe I had a 1-second-fade-up-time that led me to the conclusion that LSP is doing something wrong, here.
So, please delete this report, also. Sorry!
