### ISSUE TITLE
multi language suport

### ISSUE THREAD

**Issue by miharix** [FrancescoCeruti/linux-show-player#14]
I'm using this player at our primary school events for a quite time now and I just love it! Francesco many, many thanks for your work and for making it public!

Is it possible to add to "to do list" a integration of .qt files or similar, so it would support multiple languages without need for individual forks just for implementing a different language?

**Comment by FrancescoCeruti** [comment]
Hi, and thanks :)
I've already planned to add multi-language support, after the 0.4 release this will be added as soon as possible.

**Comment by FrancescoCeruti** [comment]
@miharix multi-language support should be completed, as soon as possible some instruction on how-to translate will be added to the wiki, let me know if you are still interested in translating to your language, Thanks :smile:
