### ISSUE TITLE
don't see icon on "list layout"

### ISSUE THREAD

**Issue by ben280** [FrancescoCeruti/linux-show-player#142]
hello,
congratulation for your program it's really work very good.
i install linux show player on linux mint mate tara. When i create a new session on "list layout" i don't see icon "play, stop, fade in out...", nothing.
There is a solution on this problem?
Thank you
Benjamin Bousquet
![capture du 2018-11-26 16-53-45](https://user-images.githubusercontent.com/45364777/49025872-d8d79780-f19c-11e8-83f9-5ccf374732a5.png)

**Comment by FrancescoCeruti** [comment]
Hi and thanks :-)
can you check if it's the same problem of issue #115 ?
Thanks :-)

**Comment by ben280** [comment]
hi,
i remove qt5ct and it work.
Thank you very much
