### ISSUE TITLE
Keep the highlighted item in the middle (as long as possible) in list view

### ISSUE THREAD

**Issue by mitscherdinger** [FrancescoCeruti/linux-show-player#146]
Hi!
In big projects or on small monitors LiSP will reach the lower end of the window, not showing the next item, anymore. I wonder if it's possible that the highlighted item will stay in the middle (once it reaches the middle and stays there as long as possible).
Of course, scrolling should although be possible just as it is. Maybe snapping back to the middle when activating the next item does the trick…? (Guess, you know what to do… :) )

**Comment by FrancescoCeruti** [comment]
Hi,
this as already been requested in #110, and it's implemented in the development version :)
