### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by FrancescoCeruti** [FrancescoCeruti/linux-show-player#15]
A list of task to accomplish to improve the user documentation.
For suggestion or errors in the documentation, leave a comment.

- [ ] i18n support for the wiki 
- [ ] Add configuration templates (cues w/ settings, JACK routing, ladi sessions...) to help quickstart shows.

**Comment by nodiscc** [comment]
Menus: https://github.com/FrancescoCeruti/linux-show-player/wiki/Menus

The contents of the current Home page needs to be moved to the Cues page.

I think separating Cues and Cues Editing pages is unnecessary at the moment.

**Comment by FrancescoCeruti** [comment]
@nodiscc It's looks like ipfs.pics doesn't keep itself the images, but it's some kind of distributed-internet stuff (https://news.ycombinator.com/item?id=10436792), so it's not ok for storing the wiki images ... for now I'll move the images on one of mine cloud-storage accounts, at least I've control over them ;)

**Comment by nodiscc** [comment]
It is possible to upload images directly to the wiki git backend (https://github.com/FrancescoCeruti/linux-show-player.wiki.git) but it requires a special syntax to embed them in the page, which I don't remember right now. And you can't do it from the web interface (requires uploading via the command line git client). Placing images on a domain you control is a good idea, we can move them to the wiki git repository later. Good to know about IPFS (not-so-permanent web).

**Comment by nodiscc** [comment]
I did some changes to the wiki: **[Wiki history](https://github.com/FrancescoCeruti/linux-show-player/wiki/_history)**

```
 	@nodiscc nodiscc 	remove cues doc from wiki home, everything has been moved to cues page. Add link to issues. 	a minute ago 	ad6f31d
	@nodiscc nodiscc 	move moving/copying/selecting/editing cues from wiki home 	2 minutes ago 	70948b9
	@nodiscc nodiscc 	add short intro, taken from website 	5 minutes ago 	da2de02
	@nodiscc nodiscc 	Updated Home (markdown) 	8 minutes ago 	b22f815
	@nodiscc nodiscc 	add media cues screenshot 	8 minutes ago 	8161f67
	@nodiscc nodiscc 	add color indicator to media cues 	9 minutes ago 	228f51c
	@nodiscc nodiscc 	add controller 	21 minutes ago 	fee6e21
	@nodiscc nodiscc 	add media settings toc entry 	24 minutes ago 	f56b4ed
	@nodiscc nodiscc 	add separator 	25 minutes ago 	c2ad128
	@nodiscc nodiscc 	add blank sections for pipeline 	26 minutes ago 	b15ccab
	@nodiscc nodiscc 	add right click info 	35 minutes ago 	ed1151c
	@nodiscc nodiscc 	add section separators 	37 minutes ago 	f27dc5e
	@nodiscc nodiscc 	add example commands page 	20 hours ago 	e94b9da
	@nodiscc nodiscc 	Updated Cues (markdown) 
```

**Comment by FrancescoCeruti** [comment]
@nodiscc, thanks for the wiki update.

About the website/wiki using the same repo, looks quite interesting, my only concern is about having (simple) multi-language support for those, did you have any experience on this?

**Comment by nodiscc** [comment]
I have no experience with localizing this kind of documentation, but it should be as simple as using filenames (`Triggers.en.md, Home.it.md, Home.fr.md...`) and linking pages properly.

**Comment by FrancescoCeruti** [comment]
I've moved the main user documentation to sphinx, into the code repository, this allow:
 * simpler versioning for the wiki
 * contributor can edit on their repositories
 * pull-requests
 * more complex controls via reStructuredText
 * easy generation of html, pdf or others with one simple command

**Comment by nodiscc** [comment]
Great choice, will you make the HTML documentation available online? (eg. sourceforge or readthedocs). The wiki could be closed to avoid confusion.

**Comment by FrancescoCeruti** [comment]
> will you make the HTML documentation available online?
Yes

> The wiki could be closed to avoid confusion.
Done

**Comment by FrancescoCeruti** [comment]
I've created a online version on [readthedocs](http://linux-show-player-users.readthedocs.io/en/latest/index.html)

**Comment by nodiscc** [comment]
Awesome. Maybe you should link to it from http://linux-show-player.sourceforge.net/

**Comment by FrancescoCeruti** [comment]
@nodiscc good idea, done :wink:

**Comment by nodiscc** [comment]
@FrancescoCeruti, I think this can be closed.
