### ISSUE TITLE
Remember last song path

### ISSUE THREAD

**Issue by Gajenthran** [FrancescoCeruti/linux-show-player#150]
I think the title is quite self-explanatory (but I still prefer to detail). The idea is to save the last cue that we add on the app. For the moment, the app go to a default path to system "music" folder. 

Actually, I already do the necessary work to change the behaviour but I would like to know if it's an interesting idea.

**Comment by FrancescoCeruti** [comment]
As mentioned in #151 this has already been implemented :-)
