### ISSUE TITLE
Request: Cue Shortcut Key <esc>

### ISSUE THREAD

**Issue by Mr-Si** [FrancescoCeruti/linux-show-player#160]
Hi there,

I have been trying to use the "Escape" button on the keyboard as a shortcut command key for interrupting one or all cues in the form of a panic button, a bit like QLab does by default, but I have been unsuccessful so far in getting the software to recognise the key when I'm trying to create it.

Is there a way you can instruct me in how to do this? or is <esc> not a key that is allowed to be used in LiSP?

Many thanks,
Simon

**Comment by FrancescoCeruti** [comment]
Hi Simon,

unfortunately right now the only accepted keyboard shortcuts (for controlling the cues) are those made of "typeable" characters, so mostly letters and numbers. I'll try to allow special characters or key sequences for next release.

**Comment by Mr-Si** [comment]
Thank you Francesco, I appreciate that greatly!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gajenthran** [comment]
I see that this feature was added to the v0.6 milestone, so I would like if it's better that I let you work on that, @FrancescoCeruti ? 

For this feature, my idea was to add two commands: one with a combobox (with special character) and another with a textarea where we can put a letter as we can see now.

An exemple of that: 
<img width="569" alt="Capture d’écran 2019-03-20 à 16 25 29" src="https://user-images.githubusercontent.com/35834540/54697298-99f39600-4b2d-11e9-93c0-65df851049c2.png">

In this example, we can also add key sequences : if we choose Escape, there will be no second word but if we choose CTRL, we have to write a second word (I forgot to add "None" in the combobox if we only want to use letters and numbers).

**Comment by FrancescoCeruti** [comment]
I was thinking to use the [QKeySequenceEdit](https://doc.qt.io/qt-5/qkeysequenceedit.html) widget, It's more flexible and should handle all the reasonable scenarios (`CTRL`, `SHIFT`, `ALT`, `CMD` (Mac), `Meta` (windows key), `F1-F12`)

**Comment by Gajenthran** [comment]
Oh ! I search about QKeySequenceEdit: it will more efficient than what I said and appropriate to what we want to do (actually i'm learning PyQt with you app, I didn't know the existence of this method).

**Comment by fralix** [comment]
Yeah, flexibility sounds great. The method proposed by @Gajenthran didn't really cover scenarios like only the w or ctrl + shift + w for water background :-)

**Comment by FrancescoCeruti** [comment]
It's now possible (develop branch) to use generic keys, and key-combinations :smile:
