### ISSUE TITLE
[develop] Removing a page in Cart Layout has unintended side-effects

### ISSUE THREAD

**Issue by s0600204** [FrancescoCeruti/linux-show-player#167]
#### Expected Behavior
When deleting a page in Cart Mode, one would expect all cues on the page to be erased, and the page removed, with no effect to the other pages.

#### Actual Behavior
Page is removed (as are all the cues on it). However, some cues on subsequent pages are also removed.

#### Step to reproduce
1. Use LiSP from the `develop` branch
1. Create a fresh showfile with the Cart Layout
1. Add two new pages.
1. To the first page, add a single cue.
1. To the second page, add more than one cue.
1. To the third page, add more cues than are on the second page.
1. Return to the first page.
1. Choose to "Remove Current Page".
1. Note that a single cue is removed from the formerly-second page.
1. Note that as many cues that were on the formerly-second page are removed from the formerly-third page.

#### Further notes
* Removing the last page in a showfile results in a lot of `'NoneType' object has no attribute 'takeWidget'` warnings.
* In the case that removing a page removes a cue, and the next page does not have a cue in the same `(row, column)` index as the first page's cue, then an `IndexError` is emitted.
* Removing a page renames all subsequent pages, even if a user has entered a custom name. (#83 / #89)

**Comment by FrancescoCeruti** [comment]
This was caused by to different bugs :man_facepalming:

Now it should work as expected, thanks for the reporting the issue :smile:
