### ISSUE TITLE
Problem with deleting selected cues

### ISSUE THREAD

**Issue by Gajenthran** [FrancescoCeruti/linux-show-player#170]
As I said in the title, there is a problem with deleting seleted cues in the branch ```develop```.
Indeed, the application remove the wrong index when we want to remove many cues (there is an offset).

For example, if we want to remove the first 2 cues, it will remove the cue at the first index and the cue at the third index. 

Moreover, I didn't know if switching to selection mode to delete a cue is finally a good idea because it required a lot of manipulation (in my opinion) : ```Selection mode``` + ```Select cues``` and ```Delete``` instead of just ```Delete```.

**Comment by FrancescoCeruti** [comment]
Hi,
I'm partially reworking the insert/move/remove part's. I'll make sure that the problem will not occur with the new changes.

> Moreover, I didn't know if switching to selection mode to delete a cue is finally a good idea because it required a lot of manipulation (in my opinion) : Selection mode + Select cues and Delete instead of just Delete

Without the selection-mode it became a bit confusing, at leas for me, I know it's a one more step to do, but right now I think it's the best approach to keep the list interactions more sane.

**Comment by FrancescoCeruti** [comment]
@Gajenthran Can you check if you have the problem with the last commit of the develop branch? Thanks :)

**Comment by Gajenthran** [comment]
Yeah, it's working (tested in MacOS, with : CTRL+A (select all), deleting cues top to bottom, deleting cues bottom to top, deleting cues in the middle, one by one, deleting only one cue). Work for me.
Great ! Thanks for the fixing.

**Comment by FrancescoCeruti** [comment]
Nice, thanks! :smile:
