### ISSUE TITLE
Minor problems (progress bar, cue status icon, undo)

### ISSUE THREAD

**Issue by Gajenthran** [FrancescoCeruti/linux-show-player#171]
I found some minor problems in ListLayout (in develop branch), that I will list you:
- When I move a running cue in the list (with selection mode):
  - [x] The progress bar doesn't work correctly
  - [x] The cue status icon disappear.
- [x] I do a wrong manipulation with the selection mode (to be honest it wasn't voluntary) : I actually select the last two cues and trying to put them at the end of the list (yes, I know it was totally stupid), after that, I try to undo the action and it show me an "IndexError: pop index out of range. Abort trap: 6". I don't think that is a real problem but I prefer to tell you.

Morever, I would like to know also if adding UP arrow and DOWN arrow to change cue is a good idea (it was present in the last version and I found it very useful). I know that we can move with arrows in selection mode. 

Hope it will help you !

**Comment by FrancescoCeruti** [comment]
I'll look into the two problems, thanks for reporting :)

> I would like to know also if adding UP arrow and DOWN arrow to change cue is a good idea (it was present in the last version and I found it very useful). I know that we can move with arrows in selection mode.

If you mean changing the current/standby cue (the one with the yellow selector, in the develop branch) you can still move it with the arrow keys  :arrow_down: :arrow_up:, like in the previous version
