### ISSUE TITLE
Custom key assign

### ISSUE THREAD

**Issue by vasconl** [FrancescoCeruti/linux-show-player#176]
I'm new to Linux and found Linux Show Player to do audio cues for musical productions usefull.

The only thing I really miss at this moment is assigning custom keyboard shortcuts. Space is already assigned to play but the ESC key does not work to stop like in QLab, Multiplay and other cueplayers does. This is a problem because we use a special hardware cue button box at our mixingdesk to control applications like this.

![q-widget-2usb-top-a1](https://user-images.githubusercontent.com/50483126/57517298-d1551680-7316-11e9-87ac-cd3f8f4af2a8.jpg)

This box works like a USB keyboard (with just 5 buttons) where the GO button is fixed space, STOP fixed ESC, etc. So a custom learning hotkey for cuelist wide operation is a must have if you wanna go with the great applications like QLab, Multiplay, etc and control them with this kind of hardware.

**Comment by fralix** [comment]
Hey, in  #172 there is a general shortcut implementation for cues. Although I didn't test it yet, you should be able to assign ESC to a Stop-All cue.

I'd still appreciate a proper solution for reassigning global shortcuts if needed, but if the work around helps this might be of lower priority.

**Comment by FrancescoCeruti** [comment]
This is already been requested multiple times. In the development version this has been already implemented

Thanks for the feedback anyway :smile:
