### ISSUE TITLE
No button images visible

### ISSUE THREAD

**Issue by vasconl** [FrancescoCeruti/linux-show-player#177]
Saw that this was an issue in 2015 and solved that time with version 0.3 release (https://github.com/FrancescoCeruti/linux-show-player/issues/1).

I've got this same issue at this moment with version 0.5.1 on Mint 19.1 Cinnamon desktop.
![20190510 No button images](https://user-images.githubusercontent.com/50483126/57518932-86d59900-731a-11e9-8b53-b6dca22375f5.png)

**Comment by FrancescoCeruti** [comment]
Hi! Se the issue #142, it should be the same.

**Comment by vasconl** [comment]
Thanks, thought I searched well about this but did not find #115 and #142.
It works after removing qt5ct.
