### ISSUE TITLE
[Develop] Crash when moving or deleting cues

### ISSUE THREAD

**Issue by radiomike** [FrancescoCeruti/linux-show-player#180]
#### Expected Behavior

Cues should move position in list, or be deleted.

#### Actual Behavior

Lisp crashes

See attached debug output. Same crash info, whether moving or deleting.

[lisplog.txt](https://github.com/FrancescoCeruti/linux-show-player/files/3260548/lisplog.txt)

**Comment by FrancescoCeruti** [comment]
Thanks for the report, it should now be fixed.
