### ISSUE TITLE
How to stop a cue after it has been faded

### ISSUE THREAD

**Issue by 74954** [FrancescoCeruti/linux-show-player#187]
Hi,
I have began playing with LiSP as an alternative to QLab and I can't work out how to stop an audio cue after it has been faded to 0 dB?
thank you

**Comment by FrancescoCeruti** [comment]
Hi!
it depends on how you are fading the cue, if you are using a "Volume Control" you can setup a [trigger](https://linux-show-player-users.readthedocs.io/en/latest/plugins/triggers.html) to stop the faded cue at the end.

If that's not the case, can you give an example of your workflow? :-)
