### ISSUE TITLE
Ctrl+S + Ctrl+N + Ctrl+S is an unexpected and sneaky way to erase everything

### ISSUE THREAD

**Issue by HugoDRV** [FrancescoCeruti/linux-show-player#189]
If you have an open file, and you create a new session, you wouldn't expect it to still be on the same buffer file as before. If you save "normally", it erases everything without a warning.
It shouldn't be too hard to make it behave like when opening the software without opening a file..?

I almost lost 10h of work because I created a pet project, hopefully I had an almost up-to-date archive.

**Comment by FrancescoCeruti** [comment]
> I almost lost 10h of work because I created a pet project

:scream: I'm sorry for that

Looks like the currently open filename is kept in new sessions, it shouldn't happen. I'll fix that and release a bug-fix version, for the 0.5 release.
