### ISSUE TITLE
[doc] Document remote module usage

### ISSUE THREAD

**Issue by nodiscc** [FrancescoCeruti/linux-show-player#19]
https://github.com/FrancescoCeruti/linux-show-player/blob/6c3446e0da3ed515877af8dbedf17574175fefc2/lisp/default.cfg#L25

Querying 127.0.1.1:8070 in a web browser results in the following error:

`127.0.0.1 - - [22/May/2016 19:17:39] code 501, message Unsupported method ('GET')`

**Comment by FrancescoCeruti** [comment]
It's the remote module, that allow to control a session by RPCs, it's based on the standard [xmlrc module](https://docs.python.org/3.5/library/xmlrpc.html) that use an HTTP transport, so it's look like a web server, but it's not

**Comment by nodiscc** [comment]
Ok thanks. Is this documented somewhere? How do I use it (examples)?

**Comment by FrancescoCeruti** [comment]
The module just provide an some kind of service, It's currently used by the `synchronizer` plugin, that allow to have a fallback session on a different machine that run the same cues at the same time.

The only thing you should do is to add the IP (a discovery function is provided) of the session you want to control, `Tools > Synchronization > Manage connected peers`

**Comment by FrancescoCeruti** [comment]
I've added a specific task in the docs issue
