### ISSUE TITLE
Config changes require a reload

### ISSUE THREAD

**Issue by paulbdavis** [FrancescoCeruti/linux-show-player#191]
#### Expected Behavior

I would expect the "Ok" button to save the config and apply it to the application immediately

#### Actual Behavior

The config options seem to only be loaded at startup, so any changed done via the UI require a restart to take effect

#### Step to reproduce

Start LiSP, change an option, observe change is not working, restart app, observe change is now in effect.

If it's difficult to implement this, a note next to the OK button would at least make it more obvious as to why settings have not changed yet (I first noticed it when I could not use my new go key binding until I restarted the app)

**Comment by FrancescoCeruti** [comment]
For now I'll add a note to make it clear, anyway I think most of the options could be applied directly, it's up to the components that use the specific value.

**Comment by paulbdavis** [comment]
This was related to the master branch, but develop has it's own issues with the config it seems (mentioned in my PR for the disable go key option)
