### ISSUE TITLE
List View buttons are blank (Raspbian Buster)

### ISSUE THREAD

**Issue by 99jj234** [FrancescoCeruti/linux-show-player#195]
When running Linux-Show-Player on Raspbian Buster the buttons (play, pause, stop) are blank. The buttons are there, but no graphics showing on them.

**Comment by FrancescoCeruti** [comment]
Hi, it's probably the same issue as #142

**Comment by 99jj234** [comment]
Thanks. Looked hard for that, but guess I can’t read after all.

Fantastic program BTW. Thank you.
