### ISSUE TITLE
Clicking on 'media info' crashes program if URI broken

### ISSUE THREAD

**Issue by laggykiller** [FrancescoCeruti/linux-show-player#199]
Version: 0.5.2
Distro: Arch linux
Step to reproduce:
1. Add cue
2. Change URI input to a non-existent file by Edit cue > Media Settings > URI input
3. Right click on the cue and press media info
4. Program crashes

Error message from terminal:
`Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lisp/modules/media_info/media_info.py", line 54, in show_info
    gst_info = gst_uri_metadata(media_uri)
  File "/usr/lib/python3.8/site-packages/lisp/modules/gst_backend/gst_utils.py", line 51, in gst_uri_metadata
    info = discoverer.discover_uri(uri[0] + "://" + quote(unquote(uri[1])))
gi.repository.GLib.Error: gst-resource-error-quark: Resource not found. (3)
Aborted (core dumped)`

Please inform me if other files and logs are needed.
This program is great, btw.

**Comment by FrancescoCeruti** [comment]
Hi!
I'll look into it, thanks for report :-)
