### ISSUE TITLE
Drag and drop move in List Layout is broken

### ISSUE THREAD

**Issue by radiomike** [FrancescoCeruti/linux-show-player#20]
When I drag a cue from one position to another the list does not reorder itself correctly. This seems to apply to all cue types. Copying a cue seems to work as expected.

Sometimes there is a visual clue, in that "Pre Wait", "Action" and "Post Wait" for the moved cue are not drawn, plus the cue line is drawn a few pixels shorter.

Seems that the cue name and cue number moves. but the actual cue remains in the original position.

Sometimes dragging a cue that is already selected results in expected behaviour, but not always.

Cues outside the drag and drop range are unaffected.

There are no obvious errors in debug output, but once this behaviour is experienced, a seg fault is reported when exiting the program.

I'm running on arch using gnome-shell 3.20.

**Comment by nodiscc** [comment]
> a seg fault is reported when exiting the program.

Note that it _always_ happens for me when exiting the program, regardless of previous operations/bugs/etc (https://github.com/FrancescoCeruti/linux-show-player/issues/18)
