### ISSUE TITLE
Multi select doesn't work

### ISSUE THREAD

**Issue by radiomike** [FrancescoCeruti/linux-show-player#21]
Currently unable to select multiple cues in list layout

This is following the master branch

**Comment by FrancescoCeruti** [comment]
Mmmh, look like that the selection-icons are not shown, If the multi-edit dialog can be opened then the cues are selected ... can you open it after trying to select some cue?

**Comment by radiomike** [comment]
Yes, muti-edit dialog does appear. Think I may have been just doing the individual cue edit by mistake.

But yes, selection icons don't appear.

**Comment by FrancescoCeruti** [comment]
Ok, seems that I've some problem loading the icons, I'm going to fix it with the next commit.

Thank for reporting :)
