### ISSUE TITLE
Don't autostart jackd

### ISSUE THREAD

**Issue by musger** [FrancescoCeruti/linux-show-player#215]
I think Lisp and any professional audio software should not simply autostart jackd when no running server can be found. It may cause problems when Lisp is started before any jackd, as Francesco already noted in https://github.com/FrancescoCeruti/linux-show-player/issues/49#issuecomment-270606247 
Instead, the software should throw an error message at startup and let the user start jackd her/himself. This will prevent an accidental and unnoticed start with jackd's default configuration, which might not be the desired configuration.

**Comment by FrancescoCeruti** [comment]
Hi! This has already been addressed in the development version, it will be available with the 0.6 version or you can try it now using the "experimental" version ([see here](https://www.linux-show-player.org/download.html))
