### ISSUE TITLE
FadeOuts do not interpolate, "zipper" noise audible

### ISSUE THREAD

**Issue by musger** [FrancescoCeruti/linux-show-player#216]
Hi, when fading out a signal using eg. the "Fade-Out all" button, the volume factors are not smoothely interpolated, making the infamous "zipper" noise audible. Best heard when using a signal with only a few partials as a low frequency sine wave, and asking LISP to fade it out over 200msec. You should hear the zipper noise due to the amplitude factors not being updated often enough and forming a staircase curve. LISP should interpolate amplitude values at audio rate. The same might apply to fade-ins and other fades as well.

**Comment by FrancescoCeruti** [comment]
So, I can reproduce the problem with a sine wave, as you suggested. I honestly never noticed during playback, I guess it becomes noticeable with tracks with very low dynamics.

The current fade steps are quite sparse (100 per second), I've tried with 1000 per second, without much improvement, increasing them too much might become a problem with the current implementation. 

Moving the "heavy lifting" to GStreamer via [Controllable Parameters](https://gstreamer.freedesktop.org/documentation/application-development/advanced/dparams.html?gi-language=c) might be the best solution.

**Comment by musger** [comment]
Interpolation noise becomes audible with signals that have less partials
(simple spectra, eg sine waves) regardless of their dynamics.
Professional audio software does interpolate at every sample. I don't
know about which things in lisp are handled in python and which in
gstreamer, but if gstreamer is your audio engine it might have to be
done there to achieve audio sample gain interpolation.

* Francesco Ceruti ***@***.***> [2021-11-20 17:47]:

**Comment by FrancescoCeruti** [comment]
Forgot to update the issue :see_no_evil: 
This has been fixed by commits f937bde800a7729539dfb7fee59f8ac02b83b355 and 75e8ed1d053fa0c516d112925496311fa0a6a88d
