### ISSUE TITLE
Opening a saved session always opens cue list opens with the last cue selected.

### ISSUE THREAD

**Issue by musger** [FrancescoCeruti/linux-show-player#217]
Opening a saved LISP session, which was saved with the first cue selected, will nevertheless always open with the last cue selected.
This is on LiSP 0.5.1 from Debian stable.

**Comment by FrancescoCeruti** [comment]
The selected cue is not saved in the session, the behavior has already been improved in the development version, where the selected cue of newly loaded shows will always be the first one. I don't even remember why it worked like that :laughing:
