### ISSUE TITLE
Don't count cues starting at zero 

### ISSUE THREAD

**Issue by musger** [FrancescoCeruti/linux-show-player#218]
In 0.5.1 at least cues are numbered in list view but this starts at zero. While we programmers like to do that I think it is counterintuitive for users. Sound designers, audio engineers, directors, composers start counting at one and it would reduce cognitive overhead to have the first cue labeled as "1".

**Comment by FrancescoCeruti** [comment]
Hi! This has already been addressed for the upcoming version. Thanks for the report :-)
