### ISSUE TITLE
Some potential enhancements

### ISSUE THREAD

**Issue by radiomike** [FrancescoCeruti/linux-show-player#22]
Just a few thoughts for possible enhancements.
- [ ] Stop-specific-cue(s). Stop all is good and being able to stop currently selected cue too. However during a complicated show it can mean operator has to step back to stop a cue in order to leave others running - potentially losing place in the cue stack. Busy awards type shows would benefit from this. I think this should link to the specific cue(s) not the list position. In terms of multiple cues, assignment should be as the collection cue?
- [ ] Stop-cue-above/last-cue. Further to above, perhaps the stop-cue-above could be default behaviour for the stop-specific-cue(s) until a specific cue is assigned?

Any of above should probably default to show which cue will be stopped.
- [ ] Sequence-cue to execute multiple cues sequentially in order (or randomly?) and possibly loop, rather than simultaneously as in the collection cue. Think background music. Can currently be achieved by editing each cue in the sequence, but would simplify programming process and reduce possibility of mistakes.
- [ ] Quick assignment of cues to actions by dragging them onto specific area of action cue?
- [x] Ability to save individual cues to disc or some kind of built in cue library. Allowing easy re-use between projects. Think saving in/out points, fade times etc with media link.
- [x] Template library for cues. Think add new media, then assign template with routing/levels/fade times etc already set. Could help save time setting up more complicated shows.

Cheers,

Mike

**Comment by FrancescoCeruti** [comment]
Some of the proposal looks quite interesting, I assume that you are talking about a `ListLayout` based show ... here some consideration:

>  Stop-specific-cue(s). Stop all is good and being able to stop currently selected cue too. However during a complicated show it can mean operator has to step back to stop a cue in order to leave others running - potentially losing place in the cue stack. Busy awards type shows would benefit from this. I think this should link to the specific cue(s) not the list position. In terms of multiple cues, assignment should be as the collection cue?

I've already thinked about this, a cue that executes a specific action on another cue, but if you think about  it, that's exactly what a `Collection Cue` does, just assign one cue and the action to be performed (e.g. stop), and you have [Stop/Start/Pause]-specific-cue(s).

> Stop-cue-above/last-cue. Further to above, perhaps the stop-cue-above could be default behaviour for the stop-specific-cue(s) until a specific cue is assigned?

This may be useful (to reduce show-programming) if you have a lot of cues that need to be stopped manually but before you go ahead starting other cues. At this point I believe it's probably easier to disable the auto-next-cue, and manually advance in  the show, or to use the right panel and stop the cue using the mouse (in the `ListLayout`), but let me know if I'm wrong :)

> Sequence-cue to execute multiple cues sequentially in order (or randomly?) and possibly loop, rather than simultaneously as in the collection cue. Think background music. Can currently be achieved by editing each cue in the sequence, but would simplify programming process and reduce possibility of mistakes.

If you are using the `ListLayout`, as I assume from the first two suggestions, you can simply use the next-action and create a sequence of cues, each one start after the one before is ended, the last one can setup a trigger and start the first one, or you can use a `Collection Cue` to start the close the loop. About the random thing, probably you want to use it for some kind of pre/post show background-music? Anyway, if with 0.5 version I succeed implementing a "hierarchical" cue-model than you can have cues that have other cues as children and that can control their behaviors easily, without cluttering the show.

> Quick assignment of cues to actions by dragging them onto specific area of action cue?

This can be useful, if it's not too complicated I'll try to have this before the 0.5 in which the UI code will probably change a lot.

> Ability to save individual cues to disc or some kind of built in cue library. Allowing easy re-use between projects. Think saving in/out points, fade times etc with media link.

> Template library for cues. Think add new media, then assign template with routing/levels/fade times etc already set. Could help save time setting up more complicated shows.

Those are interesting, and they're definitely a todo, probably those can be done as a single plugin that allow you to load a template as a cue (missing values will be to default), or "into" a cue (overriding current values), maybe with a built in library, with export/import functions, that it's probably more friendly.

Feel free to reply to any of my considerations, obviously ;)

**Comment by FrancescoCeruti** [comment]
I've merged into the master branch a (working) module that provide the ability to `add/remove/edit, import/export` presets and to `load from/load on/create from` cues.

 * The functionality are accessible from `Tools > Presets` submenu and from the cues context menu
 * Presets are created with a specific cue-type, but can be loaded on any kind of cues, obviously only the "supported" properties are loaded
 * Presets are saved as JSON files under `$HOME/.linux_show_player/presets`
 * Import/Export allow to create an archive that can be imported later on other instances

**Comment by offtools** [comment]
The "Stop above cue" or "Stop cue with cue.index: -1" generic behaviour seems in my opinion a major use case in List Layout mode.  It also reduces a lot of work, when changing the order of your cues. But sometimes in rehearsal or when doing a sound check, you skip through your show not in order. Then you also multiple cues could be fired:

Example for a list, one cue at the time (with or without fades):
Cue 1
Cue 2 (stops 1 or index -1) 
Cue 3 (stop 2 or index -1)
Cue 4 (stops 3 or index -1)
Cue 5 (stops 4 or index -1)

If you need  to play Cue 2 in a rehearsal (Cue 1 stops - its was not playing). If you then need to play Cue 5 because the do something else Cue 4 is stopped, although it was not playing at all, but Cue 2 keeps playing and needs to be stopped manual.

So I would suggest a kind of Solo Option in the Cue Behaviour Settings or Media Cue Settings. Solo means, if a Solo Media Cue is started, all other Cues Stop or Fade out. This then could be applied from a preset.

**Comment by FrancescoCeruti** [comment]
Ok for the "stop/pause/interrupt cue above" cue.

A solo mode can be implemented, but need to be defined properly, maybe in future a "rehearsal"/"check" mode may provide a different interface to simplify those kind of operations

**Comment by FrancescoCeruti** [comment]
I've added an "exec-specific-index" cue, this allow more options than simply "stop-above".
The index can be relative to the cue position or absolute, the cue-settings UI will try force a consistent index, when possible.

By default the index is `-1` (above) and `relative`, the action is `Stop`.
