### ISSUE TITLE
fadeout in a cue doesn't seem to fade out.

### ISSUE THREAD

**Issue by roboknight** [FrancescoCeruti/linux-show-player#220]
**Describe the bug**
Any attempt to fade out an audio cue when the audio ends in the middle of the audio file always ends abruptly with no fade out.

**To Reproduce**
1. Add any audio cue that has a reasonable length (at least 10 seconds or so)
2. Set the stop time somewhere in the middle of the audio cue.
3. Set the cue to fadeoutstop or fadeoutpause
4. Set the fadeout time to 1 or 2 seconds.
5. run the cue

**Expected behavior**
The audio should fade out.

**Screenshots**
N/A

**Linux Show Player version:**
- [0.5.2]

**OS Version**
 - [Ubuntu 21.04]

**Additional context**
fadein seems to work as expected.  I've tried other versions.  Different files, and different methods.  I did eventually find a way to trigger something else to generate a fadeout, but this seemed extrodinarily complex, given that every cue can have its own fadeout.  If this does actually, work, then maybe I've done something wrong, but I don't see what.

**Comment by roboknight** [comment]
As a current workaround:
Set a volume control cue.  Execute it on the start of the cue you want to fade.  Set the volume control cue to prewait for the length of time until fadeout.  Set the fadeout duration.

This seems to implement the above.  But it goes out of the way to execute what appears to be within the cue.

**Comment by FrancescoCeruti** [comment]
Hi! Thanks for the report.

What you describe it's unfortunately not yet supported, see issue #101 for more details.

**Comment by roboknight** [comment]
Thanks for pointing me to the duplicate.  I searched for “fade-out” and it never came up.  Again, thanks.
