### ISSUE TITLE
Paths to soundfiles should be stored relative to session file

### ISSUE THREAD

**Issue by musger** [FrancescoCeruti/linux-show-player#221]
I might be wrong, but does LiSP use absolute file system paths to find the soundfiles for a cue list? I was moving a directory holding the files and the session .lsp file to a different file system location and am getting red circles trying to play back a cue. Checking the file location it lists the former absolute path of the files from when I created the project. If this is the case it's a major drawback not being able to move project directories around.

**Comment by FrancescoCeruti** [comment]
In the upcoming version path will be relative to the session file :) See #23
