### ISSUE TITLE
Cue trigger instabilities

### ISSUE THREAD

**Issue by 0x2b00b1e5** [FrancescoCeruti/linux-show-player#225]
**Describe the bug**
When using media-cues, the time it takes to load a sample can take long (might be due to hardware). This would make this program useless for anything time-critical, as I have experienced during a production. 

**To Reproduce**
1. Trigger a media cue
2. Watch it take up to 3 seconds to actually fire.

**Expected behavior**
When a cue is triggered, the media should be played without delay.

**Actual behaviour**
The system first loads the sample and then plays it, which can cause an undefined amount of delay.

**Linux Show Player version:**
- 0.5.2

**OS Version**
 - Arch Linux

**Comment by FrancescoCeruti** [comment]
3 seconds are a lot ... as far as I know GStreamer doesn't load the whole file before playing it.

Can you provide more info on your hardware like CPU, HDD/SSD (where you have the tracks)?

Are you using PipeWire? I had a few strange problems using it.

It could be useful if you can provide GStreamer debug logs, you can obtain them by adding the following variables when launching the application (form the terminal):

GST_DEBUG=5
GST_DEBUG_FILE=gst.log

Like this:

```
GST_DEBUG=5; GST_DEBUG_FILE=gst.log; linux-show-player
```

**Comment by fnetX** [comment]
I assume the media type would also be helpful? Makes a difference if you have a stereo mp3 vs a multi-channel 96kHz 24bit uncompressed waveform? Or maybe some more special format which causes actual gstreamer bugs or otherwise weird behaviour when loading?

**Comment by 0x2b00b1e5** [comment]
> Can you provide more info on your hardware like CPU, HDD/SSD (where you have the tracks)?
CPU is an Intel Core i5. The bottleneck probably is the HDD, if it's a hardware bottleneck.

> Are you using PipeWire?
Not that I am aware of

> I assume the media type would also be helpful?
WAV 16bit at 44.1 KHz and some mp3s. In my experience this doesn't really matter. It happens with both MP3 as WAV files.

I'll come with a debug log later.

**Comment by 0x2b00b1e5** [comment]
So uh, LSP doesn't start up anymore after upgrading to Python 3.10

**Comment by FrancescoCeruti** [comment]
> So some HDDs have this standby/energy saving mode

Ah yes, power-saving can be problematic sometimes. I think you should be able to disable it in software.

I'll close the issue for now, but feel free to continue the conversation :)

**Comment by fnetX** [comment]
Hmm, three seconds is very weird for a spin-up It should be much less than one second, rather < 100ms? You should check your SMART data if your hard drive is fine, then.

I don't think GStreamer is flexible enough for this, but for critical shows it'd be interesting to have a high-performance back-end to cover such hardware issues. I'm thinking of a dependency model that preloads all tracks that might fire immediately into RAM, at least like the first 5 seconds. The preload would cover the current selected key, eventually following ones if they fire immediately, if an index section is selected everything that would be triggered as well as everything with a hotkey set. Essentially, this would create a preload tree that is updated depending on which cue is selected and which dependencies it got (e.g. index action which would trigger 5 following tracks immediately).

Sounds rather like an ideal world and complicated to do with GStreamer I guess, when you can't just keep all the file handlers around and read the beginning?
