### ISSUE TITLE
IndexAction cue have only one possible action

### ISSUE THREAD

**Issue by Stav88** [FrancescoCeruti/linux-show-player#227]
**Describe the bug**
IndexAction cue have only one possible action "Start'.

**To Reproduce**
1. Create à new "Index Action Cue" (Edit > Action cues > Index Action)
2. Open the edit window of the cue (right click > Edit cue)
3. Open the "Action settings" tab
4. The action combobox has only one option
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18213148/154172029-5f789327-5279-47f4-9f52-859ebab837c4.png)

**Linux Show Player version:**
- 0.5.1
- 0.5.2
- 0.5.3
- master

**OS Version**
 - Ubuntu 20.04 x68_64
 - Manjaro Aarch64 (pinebook pro)

**Additional context**
I have tried to fix the list in `Cue` class (`lisp/cues/cue.py` L125) :
```python
diff --git a/lisp/cues/cue.py b/lisp/cues/cue.py
index 7aed52f2..8902a28d 100644
--- a/lisp/cues/cue.py
+++ b/lisp/cues/cue.py
@@ -122,7 +122,19 @@ class Cue(HasProperties):
     default_start_action = Property(default=CueAction.Start.value)
     default_stop_action = Property(default=CueAction.Stop.value)
 
-    CueActions = (CueAction.Start,)
+    CueActions = (
+        CueAction.Default,
+        CueAction.FadeIn,
+        CueAction.FadeOut,
+        CueAction.FadeInStart,
+        CueAction.FadeOutStop,
+        CueAction.FadeOutPause,
+        CueAction.FadeOutInterrupt,
+        CueAction.Interrupt,
+        CueAction.Start,
+        CueAction.Stop,
+        CueAction.Pause,
+    )
 
     def __init__(self, id=None):
         super().__init__()
```
The combo box is correctly displayed. I dont know and didn't test if all thoses actions work in usage of cue.
I have tied only to use `FadeOutStop`, that's work.

**Comment by s0600204** [comment]
The behaviour you are seeing is expected if the cue is pointing at itself.

Perhaps it would help if you could tell us what it is you're expecting this cue to actually do when you press "Go".

**Comment by Stav88** [comment]
That is because I tried to isolate the bug. I did't see that it change when a change the index. But I have the same bug when I open a saved project or I uncheck the "relative" checkbox :
![image](https://user-images.githubusercontent.com/18213148/154431504-9cdc1d12-7278-4b02-850b-b31173b7548c.png)

To Reproduce (checkbox)
* Create an new media Cue (Edit > Media cues > Audio cue)
* The media cue is created at index 0
* Create à new "Index Action Cue" (Edit > Action cues > Index Action)
* Open the edit window of the index action cue (right click > Edit cue)
* Open the "Action settings" tab
* Uncheck the "Use a relative index" checkbox
* The index is already on a media cue 0
* The action combobox has only one option

To Reproduce (form saved project)
* Create an new media Cue (Edit > Media cues > Audio cue)
* The media cue is created at index 0
* Create à new "Index Action Cue" (Edit > Action cues > Index Action)
* Open the edit window of the index action cue (right click > Edit cue)
* Open the "Action settings" tab
* Change the index to -1 (to choose the media cue)
* Select "FadeOutStop" as action
* Valid the window
* Save the project in a file (File > Save as)
* Close the project
* Open the project `linux-show-player --locale en -f /tmp/test.lsp`
* Open the edit window of the index action cue (right click > Edit cue)
* Open the "Action settings" tab
* The action combobox has only one option

**Comment by s0600204** [comment]
Thank you for the more comprehensive reproduction instructions. I can now replicate the issue, and have filed a Pull Request (#228) with a fix.

**Comment by FrancescoCeruti** [comment]
Thank you all :)
