### ISSUE TITLE
Absolute filepaths in .lsp file

### ISSUE THREAD

**Issue by eldog** [FrancescoCeruti/linux-show-player#23]
Is it deliberate that the .lsp file uses absoulte paths rather than relative?

When sharing between different machines (or users) I manually edit the .lsp file to change the paths, e.g., `/home/foo/example.mp3` to `/home/bar/example.mp3`, otherwise the files don't play (because those filepaths are wrong fot that machine).

It's not a major issue, just useful for sharing between techs and the json format makes editing the files very simple (good choice :)). I guess what would be required would be a export/bundle like in qlab which would put all the media files together too.

P.S. This is an amazing/powerful project and we're using to tech shows at Edinburgh fringe this year. Thank you.

**Comment by FrancescoCeruti** [comment]
> Is it deliberate that the .lsp file uses absolute paths rather than relative?

Yes and no, currently there are a few limitation and to have relative path I should use some ugly workaround.

Anyway you don't need to edit manually the session file, under the `Tools` menu can find `Session URI Changer`, it opens dialog and from there you can load a session file and edit all the path you need and save back.

> I guess what would be required would be a export/bundle like in qlab which would put all the media files together too.

That's something that can be useful, but currently I've no idea how it works in qlab (from the user perspective), so I need to do some research :)

P.S. Thanks, that's great! :smiley:

**Comment by FrancescoCeruti** [comment]
Relative paths are now used, right now this change is only in the development branch.
