### ISSUE TITLE
ListLayout: Another Cue is selected when pressing a Keybord Shortcut

### ISSUE THREAD

**Issue by Stav88** [FrancescoCeruti/linux-show-player#230]
**Describe the bug**
After having configured a Keyord Shortcut, a search in the list is executed when the shortcut is used.

**To Reproduce**
1. At start, select "List Layout" as Layout
2. Add three cues
3. Rename the second one to begin with the letter Q (for exemple)
   * Right-click > Edit Cue
   * Open "Appearance" tab
   * Edit Cue Name
   * Click "OK"
4. Add a Keybord Shortcut on last one using the letter choosed at step 3 (Q)
   * Right-click > Edit Cue
   * Open "Cue Control" tab
   * Open "Keyboard Shortcut" subtab
   * Click Add
   * In key column, write "q" (in small case)
   * Click "OK"
  ![image](https://user-images.githubusercontent.com/18213148/154868185-260f7280-cb6c-4964-91d5-3c2a3eb65978.png)
5. Select the first cue
  ![image](https://user-images.githubusercontent.com/18213148/154868163-274adb8c-d414-42b0-bfc8-d8b3cff29c38.png)
6. Press the letter choosed at step 3 (Q)

* The second cue is selected
* The last cue is played
![image](https://user-images.githubusercontent.com/18213148/154868237-4752eca8-ced8-47fc-b217-7928eb6460ce.png)

**Expected behavior**
* The first cue is still selected
* The last cue is played

I don't know what is the expected behavior if no "Keyboard Shortcut" is configured.

**Linux Show Player version:**
* 0.5.1
* 0.5.2
* 0.5.3
* master

**OS Version**
* Ubuntu 20.04 (XFCE) x68_64
* Manjaro (XFCE) Aarch64 (pinebook pro)

**Additional context**
The search in list can be disabled by overloading the method `keyboardSearch` in `CueListView` :
```python
diff --git a/lisp/layouts/list_layout/cue_list_view.py b/lisp/layouts/list_layout/cue_list_view.py
index 8a190df8..dca8d07c 100644
--- a/lisp/layouts/list_layout/cue_list_view.py
+++ b/lisp/layouts/list_layout/cue_list_view.py
@@ -111,6 +111,10 @@ class CueListView(QTreeWidget):
         else:
             super().contextMenuEvent(event)
 
+    def keyboardSearch(self, search):
+        # disable scroll to letter match
+        pass
+
     def keyPressEvent(self, event):
         self.key_event.emit(event)

```
but you may want to keep the behavior if the shortcut is not configured.

**Comment by FrancescoCeruti** [comment]
Thanks! I confirm for 0.5.x versions. The "develop" branch apparently is not affected by the same issue.

IMHO it's an unwanted behavior. Feel free to open a pull request with a fix for the master branch.
