### ISSUE TITLE
Jack's clients ports names not shown

### ISSUE THREAD

**Issue by wargreen** [FrancescoCeruti/linux-show-player#232]
**Describe the bug**
Hi, 
For the jack output, all the names of the ports on a client are the same.
It's really difficult to deal with that when, for example, routing cue to a specific ardour's track.

**To Reproduce**
1. Open another jack client with many input
2. Got to the routing window

**Expected behavior**
See the port name in the list of the port of the clients

**Screenshots**
![Capture d’écran de 2022-02-23 21-17-03](https://user-images.githubusercontent.com/5098493/155401899-7671d372-97a3-4907-9981-47d23246e62f.png)

**Linux Show Player version:**
- 0.5.1

**OS Version**
 - debian SID with KXStudio repos

**Additional context**
Thank's a lot for your software !

**Comment by moonshaadow** [comment]
hi, 
I can confirm that the last development branch is working as expected. (Debian testing)
![Capture d’écran du 2022-03-02 23-16-18](https://user-images.githubusercontent.com/29754932/156459058-6bcfe734-34ff-42b2-b877-e225fd714b62.png)
