### ISSUE TITLE
Relative path for medias

### ISSUE THREAD

**Issue by wargreen** [FrancescoCeruti/linux-show-player#233]
Hi,
**Is your feature request related to a problem? Please describe.**
I work on my computer for now but i'll work to another computer with the actor. But i havn't the same paths !
I have a folder with all the show (medias, ardour session, LSP show), and i'd like to just move it without find the medias for all the cues.

**Describe the solution you'd like**
I think that have a checkbox "use relative path from the show file" under the media path would be very useful.

**Describe alternatives you've considered**
I've try to put a relative path manually in the URI field, but that don't work...

Thank you for this software !

**Comment by FrancescoCeruti** [comment]
See #23 and #221
