### ISSUE TITLE
Jack client strange behavior

### ISSUE THREAD

**Issue by moonshaadow** [FrancescoCeruti/linux-show-player#234]
**Describe the bug**
[Jack]
Not really a bug, but I noticed a change in the client behavior.
Former versions of LiSP were creating a client each time a cue was played, and the client was removed each time the cue was stopped.
Now the client is not removed when cue is stopped, but when cue is played again, just before creating the client again.
My question is : why to disconnect and reconnect (or remove and re-create, I don't really know) the client each time the play is triggered ? Can't we keep the client opened ?

**To Reproduce**
1. Set output on JACK
2. create a media cue
3. play many time the cue when monitoring JACK logs
4. You can see that client is disconnected then reconnected each time you play it

**Linux Show Player version:**
- Built from development branch

**OS Version**
 - Debian testing, + KX studio repos

**Comment by FrancescoCeruti** [comment]
It's due to two things:
1) How the backend is built, where every cue it's an independent GStreamer pipeline, with its own output
2) GStreamer doing what you described every time a pipeline is stopped/started

It does behave in the same way with other outputs (e.g. PulseAudio)
