### ISSUE TITLE
Cannot  edit shows with midi queues on computers with no midi device

### ISSUE THREAD

**Issue by neufena** [FrancescoCeruti/linux-show-player#237]
**Describe the bug**
I edit my shows on a Chromebook running LSP in the Linux container.  However, the container has no midi devices so I get the pictured error.

**To Reproduce**
1. On a machine with no midi devices
2. Open a .lsp file that contains midi queues
3. For each midi queue an error will be shown

**Expected behavior**
To be able to edit midi queues even if the machine has no midi output
**Screenshots**
Error message:
![Screenshot 2022-03-29 21 15 55](https://user-images.githubusercontent.com/2163835/160702302-b85e61f7-2efd-46c8-a78d-ddffb550613b.png)

Midi settings showing no devices:
![Screenshot 2022-03-29 21 16 37](https://user-images.githubusercontent.com/2163835/160702484-abf47079-0aae-4bed-aa0c-436cfb239e5b.png)

**Linux Show Player version:**
- 0.5.1

**OS Version**
 - Debian GNU/Linux 10 (buster)

**Comment by FrancescoCeruti** [comment]
This is supported in the upcoming 0.6 version :)
