### ISSUE TITLE
LinuxShowPlayer-v0.5.2-x86_64.AppImage errors - backend not loaded

### ISSUE THREAD

**Issue by keithjnewman** [FrancescoCeruti/linux-show-player#238]
**Describe the bug**
LinuxShowPlayer-v0.5.2-x86_64.AppImage errors with the message 'backend not loaded' when I attempt to add a media file

**To Reproduce**
1. Open the 0.5.2 appimage
2. Select the list layout
3. Press Ctrl M to add a media file 
4. Dialogue box with error message "Backend not loaded" appears

**Expected behavior**
The dialogue box to add a media cue should appear

**Screenshots**

**Linux Show Player version:**
0.5.2 appimage

**OS Version**
Ubuntu 22.04

**Additional context**
This occurs after doing an in place upgrade of Ubuntu from 21.10 to 22.04. It worked fine on 21.10.

**Comment by s0600204** [comment]
<details><summary>AppImage Error Message</summary>

```
00:54:37.017 WARNING:: Cannot load module: gst_backend
00:54:37.021 DEBUG:: Traceback (most recent call last):
  File "/tmp/.mount_LinuxSbQNgCU/usr/lib/python3.7/site-packages/lisp/core/loading.py", line 92, in load
    module = import_module(mod_path)
  File "/tmp/.mount_LinuxSbQNgCU/usr/lib/python3.7/site-packages/lisp/core/loading.py", line 125, in import_module
    return __import__(module_path, globals(), locals(), ['*'])
  File "/tmp/.mount_LinuxSbQNgCU/usr/lib/python3.7/site-packages/lisp/modules/gst_backend/__init__.py", line 4, in <module>
    from .gst_backend import GstBackend
  File "/tmp/.mount_LinuxSbQNgCU/usr/lib/python3.7/site-packages/lisp/modules/gst_backend/gst_backend.py", line 25, in <module>
    from lisp.modules.gst_backend.gst_utils import gst_parse_tags_list
  File "/tmp/.mount_LinuxSbQNgCU/usr/lib/python3.7/site-packages/lisp/modules/gst_backend/gst_utils.py", line 23, in <module>
    from lisp.modules.gst_backend.gi_repository import Gst, GstPbutils
  File "/tmp/.mount_LinuxSbQNgCU/usr/lib/python3.7/site-packages/lisp/modules/gst_backend/gi_repository.py", line 9, in <module>
    import gi
  File "/tmp/.mount_LinuxSbQNgCU/usr/lib/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full
```

</details>

@FrancescoCeruti, the symbol it can't find was [added to](https://gitlab.gnome.org/GNOME/glib/-/commit/e74c955335921bd2e011c14723062bfd7cf4cc37) `GLib` for version `2.69.1`.

The change should have been backwards compatible (`g_module_open` still exists), however only in the sense that `g_module_open` is now a wrapper for `g_module_open_full`.

The fact that AppImage has `GLib` partially bundled inside itself is probably not helping - at a guess, whatever symbol-lookup tables the python code uses to find GLib's symbols is bundled within the AppImage, thus it's able to find `g_module_open` (in the host-system's GLib) with little problem, but when that then wants to call a symbol the symbol-lookup table lacks...

----

@keithjnewman The *Ubuntu 22.04*-repository provided version of *Linux Show Player* not working is to be expected as `0.5.2` is not compatible with `python 3.10`. You'll need to pester the *Ubuntu* repository maintainers to backport the `0.5.3` version (already present in the repositories of in-development *Ubuntu 22.10*, itself copied over from *Debian Sid*) to *Ubuntu 22.04*.

**Comment by FrancescoCeruti** [comment]
@s0600204 Thanks for the insight.

I currently don't have much time to dedicate to this issue, also because I don't plan to support this format for future releases.

Anyway, anyone is welcome to take over the effort :)

**Comment by s0600204** [comment]
(For future reference:) As the non-running of the Ubuntu-built package on Ubuntu 22.04 is a downstream issue, a report has been filed there: https://bugs.launchpad.net/ubuntu/+source/linux-show-player/+bug/1987073
