### ISSUE TITLE
Show filename/title in the window titlebar

### ISSUE THREAD

**Issue by rdealmeida12** [FrancescoCeruti/linux-show-player#241]
I do sound effects for a local theater group here in Florida.  Linux show player works great and several other groups have asked about it.
Can you add a title line to Cart Layout ?

Thanks
Bob

**Comment by FrancescoCeruti** [comment]
Hi! do you mean custom titles in the tabs like this?
 
![image](https://user-images.githubusercontent.com/5596673/169699151-352ce80d-9e83-495c-86ea-bc147e404719.png)

It will be included in the 0.6 release

**Comment by rdealmeida12** [comment]
Here is a screenshot of the effects for "The Aldrich Family" OTR radio play we just did. I would be great if title of the .lsp were displayed somewhere on to
![linux show player](https://user-images.githubusercontent.com/8337231/169709238-b79a8d37-aa12-4d66-bfbf-40ec5a2ae392.png)
p

**Comment by FrancescoCeruti** [comment]
Oh, okay, in the window title, that should also already be in the next version.

I still need to polish a few things. But you can already try the 0.6 "experimental" version https://www.linux-show-player.org/download.html keep in mind that the save format is incompatible with the previous versions.

**Comment by rdealmeida12** [comment]
Thank You. I'll check out the new version and let you know

Thanks
Bob
