### ISSUE TITLE
unable to play audio files with spaces in path (gst-resource-error-quark: Resource not found. (3))

### ISSUE THREAD

**Issue by nodiscc** [FrancescoCeruti/linux-show-player#247]
**Describe the bug**

Playing audio files whose path contains a space does not work. Clicking on the media cue button results in an error message/popup.

**To Reproduce**
1. Clock `Edit > Media cues > Audio cue (from file)`
2. Browse and select a file whose path contains a space
3. Click the media cue button
4. A message box appears with the message: 

```
gst-resource-error-quark: Resource not found. (3)
```

```
Show details...
../gst/gio/gstgiosrc.c(323): gst_gio_src_get_stream (): /GstPipeline:pipeline1/GstURIDecodeBin:uridecodebin1/GstGioSrc:source:
Could not open location file:///path/to/SFX/010-SMP/Sonniss.com%20-%20Game%20Audio%20Monthly%20-%20 for reading: Error opening file /path/to/SFX/010-SMP/Sonniss.com - Game Audio Monthly - : No such file or directory
```

5. No audio is played

**Expected behavior**

Playing audio files should work regardless of the path.

**Screenshots**

**Linux Show Player version:**

0.5.2-1 from Debian packages

**OS Version**

Debian 11

**Comment by FrancescoCeruti** [comment]
I cannot reproduce the issue.
The path in your error looks strange, are you sure to actually have a file at `"/path/to/SFX/010-SMP/Sonniss.com - Game Audio Monthly - "`? It looks truncated
