### ISSUE TITLE
fade control for the current cue

### ISSUE THREAD

**Issue by macdroid53** [FrancescoCeruti/linux-show-player#25]
Proposal: a fade control for the current cue

**Comment by FrancescoCeruti** [comment]
Should this have separate settings from the "standard" media fade? It's only a fade or this should stop/pause the cue at the end?

**Comment by macdroid53** [comment]
Interesting question. There are several use cases for fade.

- Fade a looping cue to a different volume (probably best handled by an action cue with fade time and level specified in the action, multiple actions could fade it down, then another fade it up, etc., then fade out and stop.)

- Fade out (a special case when you just want the cue to fade away and end)

- Fade everything (i.e. a Master fade that has a app wide fade time and fades out all running cues)

Is there another use case I'm forgetting? Of course there is the Cross fade, but, is a special case all together.

**Comment by FrancescoCeruti** [comment]
mmh, ok, but the second case can be normally done by setting the media fade-out and then stop/pause the cue, so, excluding the fade all, you probably you are looking for an "emergency" stop, that allow you to stop nicely a cue that have no expected fade-out but for some reason need to be ended, right?

**Comment by macdroid53** [comment]
If I remember right:

- I created a media cue, set to loop (let's call it cue 20)
- I created an action cue to fade it to 0.00 (call it cue 21)
- when 21 executed, 20 faded to 0.00 and continued to loop

This may be desired in some situations when the intent is to fade 20 back up later.
But, in other case, fade and stop might be the desired behavior.

**Comment by FrancescoCeruti** [comment]
if I've understand correctly what you want is having a cue (that loop N times) with a fade-out when stopped, right? This is already built in the MediaCue see the [docs](https://github.com/FrancescoCeruti/linux-show-player/wiki/Media%20settings) specifcally the [Fade section](https://github.com/FrancescoCeruti/linux-show-player/wiki/Media%20settings#fade)
If needed you can stop the cue using a CollectionCue with only one cue as target.

If you are looking for a different solution you can setup a [trigger](https://github.com/FrancescoCeruti/linux-show-player/wiki/Triggers) on the VolumeControl cue that target your looping media-cue.

**Comment by macdroid53** [comment]
Is there a way to specify a different fade time (than that defined in the cue) in the trigger cue?

**Comment by FrancescoCeruti** [comment]
there is no "trigger cue" the triggers are available on every cue, they allow to execute actions on certainly cue events, see the docs page linked in my previous comment.

In your case:
* I created a media cue, set to loop (let's call it cue 20)
* I created and config an action cue to fade it to 0.00 (call it cue 21)
* In the settings dialog of cue 21, `Triggers` tab, `add` button, select the cue 20 in opened the dialog, then `ok`, first drop-down menu, select `Ended`, second drop-down, select `Stop`, confirm and close the settings (click `Ok`)
* start cue 20
* when 21 executed, 20 faded to 0.00 and stopped

**Comment by macdroid53** [comment]
Ok, so "first drop-down menu select Ended" means, when this cue (#21) ends, trigger stop on #20?

So #21 doesn't end until the fade of #20 is complete?

**Comment by FrancescoCeruti** [comment]
if you are using a `Volume Control` as cue 21, then is the cue 21 that change the volume of cue 20, and yes, the `Volume Control` cue has a duration equals to the fade time that you set in its settings so the cue end only after completing the fade.

Notice that a `Volume Control` cue, while works on the same "volume", is completely independent from the buildin fade of the media-cue.

**Comment by macdroid53** [comment]
So, in the example, cue 21 sets the volume?

Which one sets the fade time?

**Comment by FrancescoCeruti** [comment]
Yes, the cue `21` set the volume, if a "fade" duration is specified the volume is changed gradually.

If with "fade time" you mean the duration of the volume transition, the 'Volume Control` cue have it's own fade time, and fade curve type

In the following screenshot you see the `Volume Control` settings  
![schermata da 2016-08-23 16-24-42](https://cloud.githubusercontent.com/assets/5596673/17895681/25ef74b8-694e-11e6-8238-2b7bea6ab603.png)

**Comment by macdroid53** [comment]
Ok, sorry for all the questions. Normally I'd try it then, if I didn't get what I expected or didn't understand, then ask questions.

But, I'm at work with no access to my Linux PC with LISP on it. ;(

**Comment by FrancescoCeruti** [comment]
no problem :)
