### ISSUE TITLE
Hello! I have a question. How can I solve it so that two cue points are played one after the other.

### ISSUE THREAD

**Issue by zoltan4929** [FrancescoCeruti/linux-show-player#252]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by s0600204** [comment]
Could we ask that you please fill in the template so we have a better idea of what you're asking? (In other words: answer the prompts in bold in your issue description above...)

Also please tell us what version of Linux Show Player you're using.

**Comment by zoltan4929** [comment]
Thank you, I found the answer to my question in the program. Other times I study better in front of him
