### ISSUE TITLE
Linux Mint

### ISSUE THREAD

**Issue by rdealmeida12** [FrancescoCeruti/linux-show-player#262]
I don't know it this is the right place for this but I can't find any forums on linux show player.
I'm trying to run LSP on Linux Mint Cinnamon version 5.4.12.
Kernel is 5.15.-56. with 16gb memory.
Used apt to load the file (without issue)
When I click on it , nothing happens..
Check dmesg and nothing is there..
Help.. where do I go from here
Thanks 
Bob

**Comment by FrancescoCeruti** [comment]
Hi, it's probably the same problem reported in issue #250.
Can you try launching the application from the command line and post the output here?

**Comment by rdealmeida12** [comment]
Hi Francesco
 I got it !!
Thanks for the quick answer.  Here is what worked..
/usr/lib/python3/dist-packages/lisp/core/util.py line 22,
change from collections import Mapping
to from collections.abc import Mapping

/usr/lib/python3/dist-packages/lisp/core/model.py
line 21, change from collections import Sized, Iterable, Container
to from collections.abc import Sized, Iterable, Container
Again Thanks for a great program

Bob Dealmeida

**Comment by FrancescoCeruti** [comment]
Glad you solved it :)
