### ISSUE TITLE
Change the linux-show-player dot.directory to dot.config directory. (XDG Base Directory Specification)

### ISSUE THREAD

**Issue by Bligzar** [FrancescoCeruti/linux-show-player#263]
Keeping the home folder organized can be a challenge when using many different applications and the linux-show-player software create a dot.directory directly in the user's home.

The XDG Base Directory Specification would be a way to help mitigate the multiplication of dot.directory created in the base home folder.

As per the content of the folder, the simplest solution would to move the .linux-show-player directory in the .config XDG Base Directory.

Creating a symlink works, but isn't a viable workaround.

**Comment by FrancescoCeruti** [comment]
Hi, the upcoming version 0.6 is already using the XDG Base Directory Specification (not only for configs)!

Thanks :)
