### ISSUE TITLE
Trigger list starts at zero, Cue list starts at 1. Wrong songs are triggered as a result

### ISSUE THREAD

**Issue by drjswalker** [FrancescoCeruti/linux-show-player#264]
Most of it is in the header. I was setting up a simple audio cue list. The wrong songs seem to be triggered as one song ended. I noticed that the trigger list first entry was "0 Song 1" then "1 Song 2" and "2 Song 3". While the cue list first entry was "1 Song 1" then "2 Song 2" and "3 Song 3". When I asked song 3 to be triggered by song 2, it was triggered by Song 1. Other confusing configurations could be created.

John Walker

**Comment by FrancescoCeruti** [comment]
I've fixed the cue numbering, but I'm not sure about the "wrong song triggered", is was only a UI problem, the underline cue was referenced correctly.

Keep in mind that in cue settings you're asking a cue to trigger another.
As an example, in the screenshot below (Track 1 settings dialog), I've setup a trigger that will start "Track 2" when "Track 1" is started.

![image](https://user-images.githubusercontent.com/5596673/233795221-8d7b27c2-98c2-46e0-a245-0af29679017d.png)

**Comment by drjswalker** [comment]
Thank you. I think it was user error on my part looking back. Sorry for the
confusion. Thank you for fixing the numbering issue. I use this program to
great effect in magic shows. Is there anyway to link the progression
through cues to media buttons? I often perform without a sound operator and
due to the variable duration of magic effects, it would be great to be able
to trigger cues via a media button remote (usually bluetooth). If I have
missed this in the docs, I apologise.

Kind regards

John

**Comment by FrancescoCeruti** [comment]
If you're able to send MIDI or OSC messages to the computer running LiSP you can use those to trigger cues. 

Anyway for this kind of questions you should ask in the [gitter/matrix](https://gitter.im/linux-show-player/linux-show-player) chat, maybe someone else has done something similar and can give you a better answer :)
