### ISSUE TITLE
UDP Command

### ISSUE THREAD

**Issue by RyanJStu** [FrancescoCeruti/linux-show-player#277]
There is a lot of potential with this software to accept OSC/UDP commands like Qlab. I would prefer it over  QLAB if it were possible.

Any chance of adding UDP cues in parallel with MIDI and Keystroke?

**Comment by s0600204** [comment]
Hi,

The ability to receive and send OSC messages over UDP has existed in version `0.6` of LiSP since 2017.

The ability to receive and send other kinds of messages over UDP would require more information about the exact protocol desired before implementation can be considered.

**Comment by RyanJStu** [comment]
Oh awesome! Do you have any documentation on this??

**Comment by FrancescoCeruti** [comment]
@RyanJStu unfortunately the documentation for the upcoming 0.6 version is still incomplete.

Anyway similarly to the MIDI functionality, you can:
 1. create cues that can send OSC messages
 2. configure each cue to start/stop/... when an OSC message is received
 3. configure some global functions to trigger when an OSC message is received (new in 0.6)

**Comment by RyanJStu** [comment]
Hello,
I do not see version 0.6, every time I download or check GitHub, I only see v0.5.3

**Comment by FrancescoCeruti** [comment]
@RyanJStu 

here you can find the flatpak:
 https://github.com/FrancescoCeruti/linux-show-player/releases/tag/ci-develop

And here the docs:

https://linux-show-player-users.readthedocs.io/en/develop/plugins/cue_controls.html

**Comment by RyanJStu** [comment]
Thank you. I've never used Flatpak before and I don't see your program on flathub. What is the best way to install this?

**Comment by RyanJStu** [comment]
Can't seem to get it to work. And doing a --pre install still only installs 0.5. When you have some time let me know thanks!

**Comment by FrancescoCeruti** [comment]
If you have already setup flatpak on your system:

1. download the ".flatpak" file from the link I've shared before
2. Open a terminal in the folder where you've downloaded the file and run `flatpak install LinuxShowPlayer-develop-x86_64.flatpak`

This will get installed alongside the 0.5 you got from the repo. The icon is different, you should be able to find it easily.

**Comment by RyanJStu** [comment]
Thank you. Yes, I've tried that. I'm not sure what my problem is. I am running flatpak on a Raspbian OS and I keep getting the following error when attempting to install LinuxShowPlayer:

`error: The application org.linux_show_player.LinuxShowPlayer/x86_64/develop requires the runtime org.kde.Platform/x86_64/5.15-22.08 which was not found`

When I try installing via `flatpak install org.kde.Platform` my closest option is `runtime/org.kde.Platform/aarch64/5.15-22.08` which does not satisfy the flatpak install

**Comment by RyanJStu** [comment]
Apologies. Not much time with Pis and Linux so small things trip me up. I was able to install the package by calling it directly

`flatpak install org.kde.Platform/x86_64/5.15-22.08`

and now I have the LinuxShowPlayer installed (!) but when I click to open it, it does nothing.

**Comment by FrancescoCeruti** [comment]
> I am running flatpak on a Raspbian OS

The flatpak is built for x86 CPUs, it will not work if you have an arm CPU like in a Raspberry.
I'm surprised it did install at all.

Right now I don't have the time to updated the build pipeline to also produce an arm version, but 
we should get that for free once I'll put the app on Flathub.

If you want to try a manual installation, and you need help, open a Q/A discussion ([here](https://github.com/FrancescoCeruti/linux-show-player/discussions/categories/q-a))
