### ISSUE TITLE
Ability to stop cues without firing events (interrupt)

### ISSUE THREAD

**Issue by macdroid53** [FrancescoCeruti/linux-show-player#28]
When the current cue has AutoNext set and StopAll is clicked, the next cue executes.

**Comment by FrancescoCeruti** [comment]
This is the normal behavior since it's just like stopping the cue manually, even triggers will be fired, to avoid such behavior some kind of "interrupt" function/action should be added to all the cues.

This probably require some work, so to avoid further delay for the next release this goes in the 0.5, that will probably take some time to be released.

**Comment by macdroid53** [comment]
No problem with next rev. In fact, it might be worth some more discussion on how that would work. I just completed using LISP for a production so have some more thoughts, I'll post an issue.

**Comment by FrancescoCeruti** [comment]
I've integrated a new `Interrupt` action, it's similar to `Stop` but not used with triggers and likely, additionally `InterruptFadeOut` implement a fade-out with global settings for duration and type (not yet in the UI).

 * In `ListLayout` stop buttons can be configured to stop or interrupt
 * The `StopAll` cue can be configured to interrupt

**Comment by nodiscc** [comment]
_Interrupt_ action added to the wiki:
https://github.com/FrancescoCeruti/linux-show-player/wiki/Cues/_compare/3171bdce51dc60471f6351db74693a29bb6f2641...6c3f3febb6040209cb30b6ef8ab09d6670409cac.

**Comment by FrancescoCeruti** [comment]
The fade options now can be changed in the preferences dialog, maybe in the future there will be the possibility to have separate buttons to `stop` and `interrupt` but for now I've not come to a clean solution (visually speaking).

An additional note is that an interrupt-fade cannot be stopped, while stop or pause fade can be cut off.
