### ISSUE TITLE
Fails to connect with JACK in 0.6 (flatpak version)

### ISSUE THREAD

**Issue by moonshaadow** [FrancescoCeruti/linux-show-player#289]
**Describe the bug**
Error when trying to play a cue with JACK : 
```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lisp/plugins/gst_backend/settings/jack_sink.py", line 62, in __init__
    self.__jack_client = jack.Client(
                         ^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/jack.py", line 213, in __init__
    raise JackOpenError(name, self._status)
jack.JackOpenError: Error initializing "LinuxShowPlayer_SettingsControl": <jack.Status 0x11: failure, server_failed>
```

**To Reproduce**
1) choose JACK as output for a cue
2) play the cue

**Expected behavior**
the JACK module is working as expected in last realease. New rc1 version doesn't work (flatpak version)

**Linux Show Player version:**
0.6.0.dev0

**OS Version**
Mint 21.2

**Comment by moonshaadow** [comment]
No pipewire here.

**Comment by FrancescoCeruti** [comment]
Unfortunately "native" JACK is not supported by flatpak, see here for more details: https://github.com/flatpak/flatpak/issues/3622#issuecomment-631396070

We might be able to add a warning in the settings UI if we're running within a flatpak

**Comment by moonshaadow** [comment]
Thank you, that makes sense.
Could you provide instructions to build/install from sources ?

**Comment by FrancescoCeruti** [comment]
I've added some guidelines to the docs here: https://linux-show-player-users.readthedocs.io/en/develop/installation.html

If you need more info, or help, feel free to open a new [discussion](https://github.com/FrancescoCeruti/linux-show-player/discussions) :-)
