### ISSUE TITLE
Volume control cue and reducing volume

### ISSUE THREAD

**Issue by macdroid53** [FrancescoCeruti/linux-show-player#29]
In a Volume Control cue the volume to reach is a displayed as 0.00 and won't allow negative numbers. It appears to expect a percentage. But in some cases, 0.01 is not enough of a reduction.

Maybe this could be in dB or perhaps allow the user to choose % or dB

**Comment by FrancescoCeruti** [comment]
Probably I should increase the input accepted digits, and yes, having both % and dB controls it's a good idea.
