### ISSUE TITLE
Preferences not showing as expected

### ISSUE THREAD

**Issue by Phlogs** [FrancescoCeruti/linux-show-player#299]
**Describe the bug**
When I open the Preferences menu, it appears as shown in the screenshot below. I really need to access MIDI control to the GO button, quite basic but for now I can only trigger single cues separately editing one by one. Any help really welcome, and thank you for all the wonderful job done on LiSP, looking forward for new releases!

**To Reproduce**
1. Go to 'File>Preferences'
2. Not finding "Layout Controls" nor "Plugins" as shown in Docs (everything looks different, actually)

**Screenshots**
![Screenshot from 2023-12-07 12-48-48](https://github.com/FrancescoCeruti/linux-show-player/assets/153190279/834ef9b5-04b9-4c26-8441-a29bc57dea24)
![Screenshot from 2023-12-07 12-49-08](https://github.com/FrancescoCeruti/linux-show-player/assets/153190279/66e653a3-f164-4675-854b-df313538a60b)

**Linux Show Player version:**
- 0.5.3

**OS Version**
 - Pop!_OS 22.04 LTS

**Comment by s0600204** [comment]
Hi @Phlogs,

The documentation describes LiSP version 0.6 - you're running 0.5.3, which doesn't have this feature. To get the ability to configure MIDI control globally, rather than cue-by-cue, you would have to update.

Currently, the only way to get 0.6 is to either install it from a FlatPak or install it manually. Instructions for both approaches may be found in the [documentation](https://linux-show-player-users.readthedocs.io/en/latest/installation.html).

Note that 0.6 cannot read the show-files created by 0.5.x, so if you do upgrade you would have to recreate any show-file.

**Comment by Phlogs** [comment]
Thank you for the quick reply! I'm having some troubles installing in both ways described.

For the flatpak way, when I type: 
`~$ sudo flatpak install LinuxShowPlayer-master-x86_64.flatpak`
I get:
`error: The application org.linux_show_player.LinuxShowPlayer/x86_64/master requires the runtime org.kde.Platform/x86_64/5.15-23.08 which was not found`

I tried manually too, checked all the packages in the list (some I had to find the closer one, not sure I managed in all cases), and when I run:
`~/linux-show-player-ci-master$ poetry install`
I got:
`Creating virtualenv linux-show-player-7-04OIuy-py3.10 in /home/av/.cache/pypoetry/virtualenvs`
`Installing dependencies from lock file`

`Package operations: 24 installs, 0 updates, 0 removals`

 ` • Installing pycparser (2.21)`
  `• Installing certifi (2023.11.17)`
  `• Installing cffi (1.16.0)`
  `• Installing charset-normalizer (3.3.2)`
  `• Installing cython (0.29.36)`
  `• Installing idna (3.4)`
  `• Installing packaging (23.2)`
  `• Installing pycairo (1.25.1): Failed`

  `ChefBuildError`

  `Backend subprocess exited when trying to invoke build_wheel`
  
  `running bdist_wheel`
  `running build`
  `running build_py`
 `creating build`
 ` creating build/lib.linux-x86_64-cpython-310`
  `creating build/lib.linux-x86_64-cpython-310/cairo`
  `copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-310/cairo`
  `copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-310/cairo`
  `copying cairo/py.typed -> build/lib.linux-x86_64-cpython-310/cairo`
  `running build_ext`
  `Package cairo was not found in the pkg-config search path.`
  `Perhaps you should add the directory containing 'cairo.pc'`
  `to the PKG_CONFIG_PATH environment variable`
  `No package 'cairo' found`
  `Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.`
  

  `at ~/.local/share/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/chef.py:164 in _prepare`
   `   160│ `
   `  161│                 error = ChefBuildError("\n\n".join(message_parts))`
   `   162│ `
   `   163│             if error is not None:`
   ` → 164│                 raise error from None`
   `   165│ `
   `   166│             return path`
   `   167│ `
   `   168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:`

`Note: This error originates from the build backend, and is likely not a problem with poetry but with pycairo (1.25.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pycairo (==1.25.1)"'.`

 ` • Installing pyqt5-qt5 (5.15.2)`
 ` • Installing pyqt5-sip (12.13.0)`
 ` • Installing urllib3 (2.1.0)`

Then I tried anyway:
`~/linux-show-player-ci-master$ poetry run linux-show-player`
I got:
`Warning: 'linux-show-player' is an entry point defined in pyproject.toml, but it's not installed as a script. You may get improper 'sys.argv[0]'.`

`The support to run uninstalled scripts will be removed in a future release.`

`Run 'poetry install' to resolve and get rid of this message.`

`Traceback (most recent call last):`
 ` File "<string>", line 1, in <module>`
 ` File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module`
 `   return _bootstrap._gcd_import(name[level:], package, level)`
 ` File "<frozen importlib._bootstrap>", line 1050, in _gcd_import`
 ` File "<frozen importlib._bootstrap>", line 1027, in _find_and_load`
 ` File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked`
 ` File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed`
 ` File "<frozen importlib._bootstrap>", line 1050, in _gcd_import`
 ` File "<frozen importlib._bootstrap>", line 1027, in _find_and_load`
 ` File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked`
 ` File "<frozen importlib._bootstrap>", line 688, in _load_unlocked`
 ` File "<frozen importlib._bootstrap_external>", line 883, in exec_module`
 ` File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed`
 ` File "/home/av/linux-show-player-ci-master/lisp/__init__.py", line 20, in <module>`
 `   from appdirs import AppDirs`
`ModuleNotFoundError: No module named 'appdirs'`

**Comment by Phlogs** [comment]
I managed! Thank you so much! I had to install the `libgirepository1.0-dev` package too, because `gobject-introspection-1.0.pc` was missing.

Just one last obstacle on my way : I've got a 4k display on my laptop, and I found that for the version 5.3.0 I could scale correctly the application launching with this command:
`QT_AUTO_SCREEN_SCALE_FACTOR=1 linux-show-player`

With poetry it does not work, obviously...any idea? It looks a bit strange, have to resize every time the windows to read something.

![Screenshot from 2023-12-07 19-03-33](https://github.com/FrancescoCeruti/linux-show-player/assets/153190279/6ede149b-2e20-4dc0-a12c-b1f2ed233406)

**Comment by FrancescoCeruti** [comment]
> error: The application org.linux_show_player.LinuxShowPlayer/x86_64/master requires the runtime org.kde.Platform/x86_64/5.15-23.08 which was not found

You can run the following before installing LiSP:

`flatpak install org.kde.Platform/x86_64/5.15-23.08`

> With poetry it does not work

It should work, but from Qt 5.14 you should use `QT_ENABLE_HIGHDPI_SCALING=1 poetry run linux-show-player`, according to the [ArchWiki](https://wiki.archlinux.org/title/HiDPI#Qt_5)

**Comment by Phlogs** [comment]
> It should work, but from Qt 5.14 you should use QT_ENABLE_HIGHDPI_SCALING=1 poetry run linux-show-player, according to the [ArchWiki](https://wiki.archlinux.org/title/HiDPI#Qt_5)

Hello Francesco! It works! Thank you so much for helping me, looking forward to using this new version.

Maybe it will be useful for others or for you to find a solution, even after installing the `org.kde.Platform/x86_64/5.15-23.08` flatpak didn't solved the issue...but with poetry works for me, so as far as I'm concerned problem solved! Thank you again :D
