### ISSUE TITLE
List Layout runs out of space

### ISSUE THREAD

**Issue by macdroid53** [FrancescoCeruti/linux-show-player#30]
When using List Layout, if the number of cues exceeds the available space there is no longer anywhere to right click to add a new cue.

Also, Ctrl-drag to copy a cue can't drop a new cue below the last cue (i.e. the highest numbered existing cue).

Selecting Edit>xxx Cue will add a new cue to the end of the list and the user can scroll to it.

**Comment by FrancescoCeruti** [comment]
Abut the right click menu, since it's just a shortcut to edit menu when you have space, having always an empty space at the end of the list, just to show the menu, it's a bit odd, but I'll try do something, if possible.

Copy at the end it's suppose to work, so it's probably a bug in the layout code.

**Comment by macdroid53** [comment]
Having the space at the end so the right click is always available would be convenient. The bigger issue is when the list is full and you add a cue from the menu, the new cue is added without moving the list up. This leaves the new cue almost hidden.

**Comment by FrancescoCeruti** [comment]
Ah, ok, that should be possible :)

**Comment by FrancescoCeruti** [comment]
With the last commit some space is left at the end, so you can scroll e have space to right-click, and (forgot to mention in the commit) the last added cue is set as current and as a result the list is scrolled to it.

**Comment by FrancescoCeruti** [comment]
To copy a cue at the end of the list you need to drop it in the empty space at the end, in the future (probably from the 0.5) an implementation that use native (more accurate) qt functions may be possible.
