### ISSUE TITLE
Cannot create pipeline element: "Pitch" / Failed to find an svg icon for  window

### ISSUE THREAD

**Issue by KindLivingSon** [FrancescoCeruti/linux-show-player#303]
**Describe the bug**
-Changing the tone(pitch) doesn't work
-Doesn't load window's icons

**To Reproduce**
- follow the flatpak [setup guide](https://flatpak.org/setup/)
- flatpak install flathub org.linuxshowplayer.LinuxShowPlayer
- flatpak run org.linuxshowplayer.LinuxShowPlayer

**Screenshots**
![Pitch_problem](https://github.com/FrancescoCeruti/linux-show-player/assets/83143025/a8491eca-3108-4f96-8a4b-14b7c6d89c5d)
![Icon Fail](https://github.com/FrancescoCeruti/linux-show-player/assets/83143025/1e1d8174-4e02-4015-adb3-b91400f4ccc7)

**Linux Show Player version:**
- 0.6

**OS Version**
 -Ubuntu 22.04
 -Ubuntu 23.10

**Comment by FrancescoCeruti** [comment]
> Doesn't load window's icons

This happens under wayland+gnome, I've not yet found a solution, a workaround is to "disable" wayland support for LiSP using something like [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal), hopefully Qt6 will solve the issue.

> Changing the tone(pitch) doesn't work

Apparently the required GStreamer plugin is not included in the runtime, It should be possible to build an extension to make it available :thinking: I'll post here an update if I'm able to do it

**Comment by FrancescoCeruti** [comment]
I've update the Flathub release to fix in `Cannot create pipeline element: "Pitch"` error
