### ISSUE TITLE
Thoughts after a real show

### ISSUE THREAD

**Issue by macdroid53** [FrancescoCeruti/linux-show-player#31]
Having just completed using LISP for an actual production, here are some thoughts on various things.

Overall impression is really good. Great piece of software for an application area currently under served by FOSS offerings!

I used it exclusively in list layout, since this mirrors the linear progression of a theatrical performance, at least in my mind.

Overall the program is very stable (other than the seg fault on exit...doesn't matter much, since it is on close.)

There are some usability features that are found in similar programs that I missed. (Could be as a new user, I just don't know or haven't found them yet...)

Having a fade time defined for each cue is good. But, I think that should be the default for that cue and having a collection cue be able to override that would be good. It would also be nice to have a selection in the collection cue that a fade out with a specified time.

A set of "master controls" somewhere on the gui would be nice. They would include:
- Master volume (much like the main fader on a mixer)
- Fade (fades the currently highlighted cue. This could actually be on the running cue's panel on the right that has pause, stop, run, and the time line now.
- Fade All (fades all running cues. Fade time based on some system wide setting)
- Stop (stops currently highlighted cue. This is in the per cue panel on the right now, and is fine)
- Stop All (Stops all running cues, doe not trigger anything else. Sort of an emergency stop.)

I found it a problem when I wanted to fade a running cue that was already quiet to a level lower than the dialog on stage. Basically fading to a very low level and 0.01 wasn't low enough.

On the active cue display panel on the right when a cue is running, it would be nice to have a volume control, a fade control and a level display and control.

It would be nice to have the background color of a cue indicate if it is a media, action, etc. cue.

It would be nice to have a set of icons on the cue line that indicates, for example, it is set to loop.

It would be nice to be able to drag the timeline indicator in a running cue. i.e. move and jump forward or back on the time line while the cue is running. (For those situations where the director says can we start at the second chorus? or can we start  just before the end? This of course won't happen during a show, but, during rehearsals...all the time.)

Some sort of indicator for an action cue the tells what cue/s it's going to act on.

I might remember more...but, that's all my early coffee has shaken from my memory at this point. :)

Regards,
Mac

**Comment by FrancescoCeruti** [comment]
Ok, some of them are duplicated of the previous issues, so consider the comments on those.

First, about the colors/indicators and likely, it something already planned: my idea is to have icons on the rows to easily distinguish the cue types, and values for loops and target, all of that for the 0.5 or later, the icons may be a bit long because I need to find something freely usable or to build (maybe using something as a base) them myself (or find someone else).

> It would be nice to be able to drag the timeline indicator in a running cue. i.e. move and jump forward or back on the time line while the cue is running. (For those situations where the director says can we start at the second chorus? or can we start just before the end? This of course won't happen during a show, but, during rehearsals...all the time.)

This is already possible from the pre-pre-pre-pre-never-published-alfa :laughing: I use this functions myself a lot
![schermata da 2016-08-22 15-29-39](https://cloud.githubusercontent.com/assets/5596673/17856332/4af8eb1c-687d-11e6-8a1d-1f180db34e6f.png)
you can drag the "blue" bar, the only inconvenient is that using the ListLayout you need to start the cue before.

About the fade/stop/fade-all, are those really needed as independent functionality outside of a cue (so as gui component like a button)? if possible I'd like to have (where possible) all the live controls as cues to avoid cluttering the interface with too many controls and as you said

> [...] linear progression of a theatrical performance, at least in my mind.

but I make very few shows and usually those are quite simple, so let me know if my idea is too restrictive

**Comment by macdroid53** [comment]
It's a bit hard to see, but take a look at a Windows world example CuePlayer Premium: http://www.baxeldata.com/2015/services.htm There is a cluster of the "master" controls on the right. Play, Pause, Stop, Fade work on the currently selected cue, Stop All, Fade All, etc. work on all running cues.

Also, note the icons on the lines indicate various settings of the cue.

Um...I might be able to create icons. What format? How many pixels, etc.?

I wouldn't be able to work on them until mid Sept. though.

**Comment by nodiscc** [comment]
icon sets with Free licenses: https://github.com/nodiscc/themes-icons/tree/master/ICONS

**Comment by nodiscc** [comment]
> About the fade/stop/fade-all, are those really needed as independent functionality outside of a cue (so as gui component like a button)? if possible I'd like to have all the live controls as cues

I'm also in favor of putting all controls into cues, and leave the main UI as blank as possible. You should be able to build your own "master" section with all the required controls and save that show as a template.

**Comment by nodiscc** [comment]
> Some sort of indicator for an action cue the tells what cue/s it's going to act on.

Like the color indicator in [Media cues in Cart Layout?](https://github.com/FrancescoCeruti/linux-show-player/wiki/Cues#media-cue)

**Comment by nodiscc** [comment]
> It would be nice to be able to drag the timeline indicator in a running cue. i.e. move and jump forward or back on the time line while the cue is running.
>> This is already possible from the pre-pre-pre-pre-never-published-alfa :laughing: I use this function myself a lot;you can drag the "blue" bar, the only inconvenient is that using the ListLayout you need to start the cue before.

This would be useful.

**Comment by nodiscc** [comment]
>It would be nice to have the background color of a cue indicate if it is a media, action, etc. cue.

In Cart Layout you can set the cue's background color, but not in List Layout. A 20px wide block on the left of each cue, displaying the cue's selected color would be great.

**Comment by macdroid53** [comment]
nodisc said:

"You should be able to build your own "master" section with all/just the required controls and save that show as a template."

Are saying make a set of cues that provide these functions? I don't think I understand what you're describing.

If you are describing a set of cues that are included in every show and need to stay at the top of a list layout (or cart)? That would defeat the purpose if you have 100 cues and need to scroll to find the master controls.

**Comment by nodiscc** [comment]
> Are saying make a set of cues that provide these functions? 

Yes.

**Comment by macdroid53** [comment]
Then, as I noted, scrolling up and down to find them for a show with large numbers of cues would be painful.

If something changes during a production (someone drops a line for example), to compensate I need to go looking for the master "stop or fade all". Not convenient, IMO. :)

**Comment by nodiscc** [comment]
I agree. There are a few workarounds (Bind keyboard or MIDI keys to your master cues, put your master cues in the middle of the list, ... ) but a way to keep the master cues always-on-top would be best.

**Comment by macdroid53** [comment]
So, a way to define a set of cues that never scrolled in a list, or locked in cart, or (thinking crazy here...) maybe a dialog that contained only select cues that could be positioned as the user desired.

**Comment by macdroid53** [comment]
The "bind keyboard" deserves some consideration.  I own one of these: http://techkeys.us/products/sixkeyboard and it is quite handy.

**Comment by FrancescoCeruti** [comment]
@nodiscc  thanks for the links, I will take a look at them

> In Cart Layout you can set the cue's background color, but not in List Layout. A 20px wide block on the left of each cue, displaying the cue's selected color would be great.

> Let me know when I should report separate issues to break this all up.

yup, this may need it's own discussion (e.g. better only a block or all the row colored? text color? etc..)

> Yes it would be a problem with 100+ cues. @FrancescoCeruti can there be a way to "stick" some cues to the top (when you scroll, scroll everything but keep these cues visible? Display them in a separate list on top? I don't know )

At this point is a lot simpler (at least for the coding) to have those controls as widgets like the pause-all/resume-all/stop-all in the top right of the list layout (maybe together), and allow to show/hide them.

> The "bind keyboard" deserves some consideration. I own one of these: http://techkeys.us/products/sixkeyboard and it is quite handy.

Never used one of those, but until you are able to produce some text with the "keys" you can use them as shortcuts.

**Comment by macdroid53** [comment]
The sixkeyboard allows you to program each key with whatever character or string you desire.

So it could, indeed, be used for shortcuts.

**Comment by nodiscc** [comment]
I just reported the issues above #33 #34 #35 #36, feel free to close this issue if you want

**Comment by FrancescoCeruti** [comment]
yeah, it's better to move all the arguments on the specific issue to avoid confusion, thanks.
