### ISSUE TITLE
Can't move the cues in List Layout

### ISSUE THREAD

**Issue by Mouflon23** [FrancescoCeruti/linux-show-player#317]
I have installed the software on ubuntu 22.04, everything work perfectly but drag and drop cues to move it doesn't work.
Maybe I didn't get where to drag and drop it, but I am pretty sure it supposed to look like the software on mac to not named it !

**Linux Show Player version:**
- 0.6.3

**OS Version**
 - Ubuntu 22.04.4 LTS

(Just adding that, I would love to make tutorial on this software, can I ?)

**Comment by Mouflon23** [comment]
Figured out that I can not CTRL + Drag to copy them. I can only clone them by right clicking and use "clone cue"
The thing is "I can't move them in any way"...

**Comment by Mouflon23** [comment]
OK... I am dumb, find my problem !
State => Selection Mode enabled
Now I can move all the cues ! Wonderful ! 😆
I think we really need a tutorial on Youtube ! I will do that 😊

**Comment by FrancescoCeruti** [comment]
Mmmh, the docs are not clear about this, I'll update them
