### ISSUE TITLE
Fade All/Stop All/Master volume controls

### ISSUE THREAD

**Issue by nodiscc** [FrancescoCeruti/linux-show-player#33]
Followup to #31 

> About the fade/stop/fade-all, are those really needed as independent functionality outside of a cue (so as gui component like a button)? if possible I'd like to have all the live controls as cues
> 
> > I'm also in favor of putting all controls into cues, and leave the main UI as blank as possible. You should be able to build your own "master" section with all/just the required controls and save that show as a template.
> > 
> > A caveat is that you must make sure your master section is always visible (in case of long cart/list layouts).
> > 
> > > Then, as I noted, scrolling up and down to find them for a show with large numbers of cues would be painful.
> > 
> > Yes it would be a problem with 100+ cues. @FrancescoCeruti can there be a way to "stick" some cues to the top (when you scroll, scroll everything but keep these cues visible? Display them in a separate list on top? I don't know )
> > 
> > > So, a way to define a set of cues that never scrolled in a list, or locked in cart, or (thinking crazy here...) maybe a dialog that contained only select cues that could be positioned as the user desired.
> > > 
> > > > At this point is a lot simpler (at least for the coding) to have those controls as widgets like the pause-all/resume-all/stop-all in the top right of the list layout (maybe together), and allow to show/hide them.
> > > 
> > > There are a few workarounds (Bind keyboard or MIDI keys to your master cues, put your master cues in the middle of the list, ... ) but a way to keep the master cues always-on-top would be best.
- [x] <del>Master volume slider</del> refer to issue #24 
- [x] Stop All Cues button
- [x] Fade All Cues button

> > Stop current cue is already possible (?) by using directly the cue's Stop button. A manual Fade Cue button here would be nice (the fade time would be set globally for the show?)

**Comment by FrancescoCeruti** [comment]
This "Stop All" should it's more like an "Interrupt All" that do not fires next-action/triggers and likely, a standard "Stop All" is already present. Maybe can be done with an optional fade-out (global setting for the duration) to stop the cue nicely when possible (media cues).

**Comment by FrancescoCeruti** [comment]
So, it's a while since all the discussion, and I've got a question (probably a stupid one), is the `FadeAll` intended as "all the running cues (fade-able or only media?) faded-out but remain running"?

**Comment by FrancescoCeruti** [comment]
I've implemented fades on cues, fade-in and fade-out on All and single cues, let me know :)
