### ISSUE TITLE
Just saying thanks

### ISSUE THREAD

**Issue by dj-foxxy** [FrancescoCeruti/linux-show-player#39]
We were teching shows at this year's Edinburgh Festival Fringe in Scotland. Linux Show Player did everything that we needed. Used for full runs of All Aboard the Marriage hearse, A Series of Unfortunate Breakups, and Melancholic Poontang.

I was going to suggest down arrow on auto follow cues, but just got the new version and they are already there.

Thanks.

**Comment by FrancescoCeruti** [comment]
Great!! Happy to know that LiSP has been useful to you :smile: and thanks for the feedback!
