### ISSUE TITLE
[crash] drag drop remove then undo

### ISSUE THREAD

**Issue by PaolaShultz** [FrancescoCeruti/linux-show-player#40]
If you try to rearrange and move song to end, you can accidentally remove it by releasing it bellow list. If you press undo, program crashes. I think drag & drop there should put cue last, not deleted.

**Comment by FrancescoCeruti** [comment]
Didn't notice before, it should move it at the and, sorry :sob: 
For now try to not drop the item below, you can still move the item at the end, when the drop indicator (white line) is below the last item.
