### ISSUE TITLE
Question on Pause Buttons behaviour

### ISSUE THREAD

**Issue by offtools** [FrancescoCeruti/linux-show-player#43]
Hi,

just a question: the pause/playing buttons are also triggering fades set inside the cues. Is this intented?

Thanks. offtools.

**Comment by FrancescoCeruti** [comment]
Yes, it's intended.
With the next version (0.4.2) it's planned to have separate actions for `Stop / FadeOut-Stop / Pause / FadeOut-Pause` at this point I can add the possibility to chose those buttons behaviors.

**Comment by offtools** [comment]
good news. thanks
