### ISSUE TITLE
Question on custom gstreamer elements

### ISSUE THREAD

**Issue by offtools** [FrancescoCeruti/linux-show-player#44]
Hello,

can you add an example for a custom gstreamer component in the wiki?

Thanks.

**Comment by FrancescoCeruti** [comment]
Ok, it can be useful, asap I will write a short guide with some examples.

**Comment by FrancescoCeruti** [comment]
I've added a [page](https://github.com/FrancescoCeruti/linux-show-player/wiki/GStreamer-Custom-Element) on the wiki, let me know if it's clear enough .

**Comment by offtools** [comment]
Hello,

It's clear now. very interesting possiblities.

thanks a lot.
