### ISSUE TITLE
Join the team - Transifex

### ISSUE THREAD

**Issue by pafri** [FrancescoCeruti/linux-show-player#45]
There is Czech team missing in the list of available languages. Also, could you add this for me to mecame the member/reviewer and finally coordinator of Czech language team. The files are translated for several days, so I would like to upload them. :-)

**Comment by FrancescoCeruti** [comment]
Sorry I didn't notice before, sometimes transflex "forgot" to send me email-notifications.
I've added you as a reviewer since for now I don't think I need coordinators.
