### ISSUE TITLE
load_session creates new cue.id causes trigger not to work [git:master]

### ISSUE THREAD

**Issue by offtools** [FrancescoCeruti/linux-show-player#46]
Hello,

there' a problem with loaded sessions using triggers. Triggers are not shown in the CueEdit Widget and do not work.

Reason:
"Application._load_from_file" creates a new cue.id which differs from the id of the previous session.
This causes a problem with triggers, which stills holds the old cue.id. 

before saving:
Cue 1 
cue.id 5d127eb3-0af4-4092-8f72-0d7267f8ab60
Cue 2 
cue.id 06df0367-c927-4f80-9adc-197b86673c79
cue.id in trigger 5d127eb3-0af4-4092-8f72-0d7267f8ab60

after loading: 
Cue 1 
cue.id eb2e659f-6298-4b4c-92eb-3a67df7450a1
Cue 2 
cue.id 3f0c3ca0-796f-42b6-8e73-de80a1ace058
cue.id in trigger 5d127eb3-0af4-4092-8f72-0d7267f8ab60

After loading the saved session the cue.id in the trigger references to a non existing cue.id.

This bug effects only the current git version, 0.4.1 is fine.

**Comment by FrancescoCeruti** [comment]
Thanks, I've notice the triggers problem but not the actual cause, thank for figuring it out. I will push a fix as soon as possible.
