### ISSUE TITLE
MIDI Cue - channel 0 = channel 1

### ISSUE THREAD

**Issue by aroomthedoomed** [FrancescoCeruti/linux-show-player#48]
hey! congrats for the soft improvements. midi cues are such a good feature. I can now manage to handle audio cues and light cues on linux in the same cue list. it's so good to be able to have another choice than qlab and macos.

I've managed to control D::Light (mutliplatform light soft : www.getdlight.com) with a midi CUE, but I've been struggling because the midi channel on LiSP are not correct ? I've tracked the issue with KMidimon and midi channel 0 on LiSP is in fact midi channel 1 in KMidimon and D::Light

I hope it's not just on my system?

a request/remarque regarding midi : Midi Show Control (MSC) messages are a great asset to control other soft/hardware. for example you could load a specific Cues in D::Light or on a light desk via MIDI IN with the GO message. it would be nice to have MSC messages implemanted in LiSP as well

thanks for your work. I will give LiSP a lot more attention for now on.

**Comment by FrancescoCeruti** [comment]
Hi, the midi channels are correct,in LiSP the midi-channel are shown as 0-15, actually all the software use this values under the hood, but usually the midi channels are referred as 1-16. I will change that to avoid confusion.

About MSC, I will take a look at it, but don't expect anything too soon ;)

**Comment by FrancescoCeruti** [comment]
Done in 7a82e55dde04346b96bf7445b53cb56212e390bb

**Comment by KnardDavy** [comment]
Hello,

I'm searching some help to manage a lighting program (QLC+) with a midi cue, using LiSP (Linux Show Player).
I'm french, and i don't know MIDI very well !
If aroom is always here, i think he would be able to help me !

I just need to know how i can create a MIDI cue in LiSP to manage "next cue" in QLC+ !

Thank for your help (even I know the subject is very old !!) ;)

Knard Davy

**Comment by aroom** [comment]
Hello

You can try to get help on this wiki:

https://getdlight.com/wiki/index.php/LinuxShowPlayer

I’m sure that QLC+ can handle OSC messages. 

Bye ✌️

**Comment by KnardDavy** [comment]
Thank you aroom !

I'll take a look... I'm so lost with these different configuration ! ;)

Bye
