### ISSUE TITLE
Crashes Without Jack

### ISSUE THREAD

**Issue by actor125** [FrancescoCeruti/linux-show-player#49]
First, Thanks so much for this software! I recently ran a theatre show here in New York City with your software. I used it in conjunction with QLC and a custom video wall program that a friend built for me. During the course of the show run there were a few kinks. I'll make individual threads for each of them.

If Jack fails to load, or loads in and incorrect preset, LiSP would crash when trying to open the file. Several times during the run Jack went  down for unknown reasons. We would get Jack right back up, but LiSP would not start or crash immediately after loading.

When LiSP would finally load without crashing all of the Jack connections would be re-patched to defaults, and we would have to go back and re-patch the entire show. We did this for 90+ individual cues in the middle of 2 separate shows. (I feel dumb now, I just learned about the multi-edit function!)

**Comment by FrancescoCeruti** [comment]
Thanks,
sorry for the inconvenient :grimacing: I'll investigate the crash problem.

About the re-patching, it shouldn't happen, unless the input-port names have changed, or are not available, but I'm not 100% so I'll try to figure out the problem.

**Comment by actor125** [comment]
Thanks!!

Loving this program

**Comment by FrancescoCeruti** [comment]
So, I've tested using a default setup (LiSP -> system), killing the server make all the "Jack" track unusable and I need to reload the session but LiSP doesn't crash, and it load correctly.

I'll try to simulate some more complex situation, but I'm no Jack expert and GStreamer doesn't help me when it comes to manage the server shutdown, so for now I can't promise a 100% solution.

A useful note is that LiSP will try to start a new server if one cannot be found, this may cause some problem if you load LiSP session before your Jack session.

**Comment by FrancescoCeruti** [comment]
So, I've tested a case where the `input` port are missing, still no crash, and the settings are preserved (even if not displayed in the edit-dialog), if the port are restored, when the media-cue is started those are connected correctly.

If you (or someone) are able to reproduce (maybe not during a show) and provide more information it may be helpful

**Comment by actor125** [comment]
Thank you for taking a look at that. I've recently started getting some
other weird errors on my machine which may or may not be related. I'm going
to reload the machine and then try to reproduce the problem. There is a
chance it may have just been an error with my install of Ubuntu that was
causing a problem.
