### ISSUE TITLE
Global hotkeys/MIDI/etc...

### ISSUE THREAD

**Issue by aroom** [FrancescoCeruti/linux-show-player#58]
hi,
just a feature request. or maybe I just didn't see where to configure it. but it seems impossible yet to assign a midi message (note for example) to GO and other global function (Stop, Pause, Play, Next Cue, Previous Cue)

cheers

**Comment by FrancescoCeruti** [comment]
Currently there isn't such options.

This should be quite "simple" to provide as a functionality of the `controller` plugin, this should allow to configure keyboard/MIDI/... to trigger global functions.
