### ISSUE TITLE
Trigger behavior and OSC support

### ISSUE THREAD

**Issue by aroomthedoomed** [FrancescoCeruti/linux-show-player#6]
hi. I encounter an erratic behavior with the trigger option. sometimes if you re-launch a cue, it could start the linked one, even if it's supposed to stop it. and vis versa.

nice piece of software so far. some request : 
- it would be great to be able to use is with multi channel output.
  -it would be great also to be able to configure osc messages to trig cues
- an option to configure the GO (spacebar) in midi / osc / keys
- double clic on a cue should open the edit menu also.
  
  but anyway, thanks for your work, I'm really considering using it live someday. the trigger option works fine if you go simply thru the sequence. but if you need to go back and relaunch a cue, you can have a bad surprise.

I'm still testing the soft, I had some crash. the only one I can recall right now is when I clic on remove in the triggers menu, without selecting any trigger.

cheers

**Comment by FrancescoCeruti** [comment]
Hi, in the current version, the option you see is the event that trigger the selected cue, something like "when the cue go in <state> trigger <cue>". When triggered, the cue, depending on the current state and settings, can do the following: stop->play; play->stop; play->pause; pause->play.
In the new version you can choose what to do with the selected cue.

  * OSC is a good idea, it needs a bit of research but you can consider it on the TODO list
  * even doubleclick is a good idea ;)
