### ISSUE TITLE
Bug CueControl 

### ISSUE THREAD

**Issue by MarioGreenway** [FrancescoCeruti/linux-show-player#71]
I have recently downloaded the software and really like it, it reminds me a little bit of Multiplay for windows( not under active development, no MIDI Triggering implemented ) , but have a few questions, found some bugs:

Bug:
When clicking "Remove" in 
  - Cue Control --- Keyboard Shortcuts or --- MIDI Controls,
and there is no Shortcut or MIDI Control in the list, ( empty window ), the program crashed. I tried it several times and it happened every time.   

Question: The "Restart All" Button in List Layout kind of works as a Play - Button for all paused Cues, is that the intended behavior?

~~In Addition, in my opinion it would be great to be able to trigger the cues with other MIDI commands than "note on" and "note off"  - As it is possible to send control_change or program_change, why not receive it? Many digital mixing boards send program_change commands, every time one changes a scene. That would make the MIDI-Trigger much more flexible.~~ See issue #72

**Comment by FrancescoCeruti** [comment]
> Cue Control --- Keyboard Shortcuts or --- MIDI Controls,
and there is no Shortcut or MIDI Control in the list, ( empty window ), the program crashed. I tried it several times and it happened every time.

The corner case I never check, thanks for reporting

> The "Restart All" Button in List Layout kind of works as a Play - Button for all paused Cues, is that the intended behavior?

Yes, it restarts all the paused cues.

> In Addition, in my opinion it would be great to be able to trigger the cues with other MIDI commands than "note on" and "note off".

It shouldn't be too complex, I'll open a new issue for this to keep it separate from the bug

**Comment by MarioGreenway** [comment]
Regarding the "Restart All" Button, - in my understanding, restart means to actually replay the cue from the beginning. A better word would be a "Resume All" Button, that wouldn't be that misleading. 
Anyways, thanks for looking into the bug.

**Comment by FrancescoCeruti** [comment]
@MarioGreenway :+1: you're right
