### ISSUE TITLE
Go - Button behavior

### ISSUE THREAD

**Issue by MarioGreenway** [FrancescoCeruti/linux-show-player#74]
So after continuing my experiments with the software, I noticed some strange behavior of the GO-Button.
If one GOes a CUE when it's active or running, the CUE is stopped. So the GO-Button behaves like the 
Stop - Button of "Playing Cues" menu. This function seems not to be the best in my opinion, as the GO Button may be triggered by accident, and then immediately Stops the cue. 

If one could disable the GO - if the selected cue is still running, that would be a great option, especially as the GO is a second STOP Button, if GO is pressed with a running CUE selected. 
(Visual feedback in that situation would of course be brilliant, making the GO letters red if disabled) 

Regarding the Selection of the next cue: 
There is this option to Autoselect the next cue, 
I would love the option to Autoselect the next cue once the first cue played through, just to avoid activating the next cue accidentally. Who knows what happens in stressful situations...
Currently there are these options autonext and autofollow, how about an autoselect-next there :)

Currently I am almost at that point where I would use your software for musical theater, but there are still these small annoying bugs... apart from those, the software is really nice to use, great GUI and intuitive use. I will experiment with multiple outputs and Jack next :) , I already read about the limitations there, but maybe one can avoid these somehow... 
I really hope for the next version, as this seems to be the only audio cue software that I like under Linux

**Comment by FrancescoCeruti** [comment]
> If one could disable the GO - if the selected cue is still running, that would be a great option, especially as the GO is a second STOP Button, if GO is pressed with a running CUE selected.
(Visual feedback in that situation would of course be brilliant, making the GO letters red if disabled)

Okay, maybe the GO can use a color-code to display the selection status, and an option to allow only to start cues.

> Currently there are these options autonext and autofollow, how about an autoselect-next there :)

It may be a good compromise between manually and auto-selecting the next cue :+1:

**Comment by MarioGreenway** [comment]
As you said, the GO- Button should only be able to start cues, not stop them. That's pretty important from the end users perspective in my point of view.

**Comment by FrancescoCeruti** [comment]
To clarify the way it's working right now, currently the go button is the visual counterpart of the space-bar (or whether the user set) and vice versa (they refer to the same function), so it's just executing the pending action of the cue (stop->start, start->stop|pause, ...), and it's mainly indented to work with the autoselect option enabled, otherwise, as you said before, it may cause troubles.

**Comment by MarioGreenway** [comment]
Thanks for that information. That would mean that only one function needs to be changed then :) 
As I believe that the space button should also not be able to stop the active, selected cue in that case. 
In theater i usually don't need to stop the cue anyway... I just set the start end values accordingly. 
If, then I would do a fade out, as long as it isn't anything spontaneous  ::

I started to suspect that the Play - Stop, and GO- Space were all the same function, because if that were the case, changing the behavior of GO would be kinda tricky.

**Comment by FrancescoCeruti** [comment]
> In theater i usually don't need to stop the cue anyway... I just set the start end values accordingly.

I try to accomodate the needs of everyone, someone prefer to stop/fade a track (background sounds/music) when needed, especially if the timing of the scene is not perfect (especially with amateurs).

The ideal solution is to give the option to choose to the user :wink:

> I started to suspect that the Play - Stop, and GO- Space were all the same function, because if that were the case, changing the behavior of GO would be kinda tricky.

I'm using a dispatcher function, but the single actions can be used, that's the case for stop/start buttons :)

**Comment by MarioGreenway** [comment]
Yes, of course. The possibility to enable or disable the GO functionality to Stop the cue would be the best. 
I agree that for many people this may be a very useful feature, especially as they may be used to play - pause playback with space.
