### ISSUE TITLE
Bug with .mp3 files with changed start-position in media cue settings

### ISSUE THREAD

**Issue by MarioGreenway** [FrancescoCeruti/linux-show-player#76]
Very weird and problematic bug with mp3 files:
If one sets a start-position in the media cue settings, then the file won't play, but LiSP will reserve a few MB of RAM.
So if one sets the -1 repeat value, one can wait a few seconds and ones whole RAM is full, the Computer crashes. ( I have 8GB that were full within 10sec. )
With .au files, the files don't playback if one sets a start-position else than 0, but the RAM Problem doesn't occur. 
That only seems to happen with .mp3 files. 
So after my computer crashed, I tried to replicate that error and find the mistake... often needing to kill the task to avoid another crash. 
I tried it with other file types such as flac, wav, ogg
The Problem didn't occur with any other file type. 
I also tried a different mp3 file as I suspected that file may be corrupted, but that wasn't the case. 

Another Problem: with .au files, if one clicks MediaInfo the Software crashed, happens every time.

**Comment by FrancescoCeruti** [comment]
Mmmh, looks like a bug with the GStreamer version used in the AppImage (my local installation works perfectly), the problem is that seek doesn't work on mp3 files (not all of them apparently), for now you can try a manual installation, I'll try to build an AppImage with a newer version of GStreamer.

> Another Problem: with .au files, if one clicks MediaInfo the Software crashed, happens every time.

For some reason GStreamer return a null object is some cases I wasn't aware of, I'll fix that for the next release

**Comment by MarioGreenway** [comment]
Thank you! I really like how active the development of this software is! By the way, I translated the software to German, so another Language Support may be possible in the future.

**Comment by FrancescoCeruti** [comment]
>  I translated the software to German

Great :+1:

**Comment by FrancescoCeruti** [comment]
Those problems are solved in the new `0.5-1` build, see #90, the version con be download is attached to same release and replace the older one.
