### ISSUE TITLE
Replacing GStreamer with <something>

### ISSUE THREAD

**Issue by FrancescoCeruti** [FrancescoCeruti/linux-show-player#77]
In the beginning GStreamer was a easy pick, within various development cycles I've found it to be a lot more complex then what I initially thought, plus I've encountered annoying bugs in more occasions.

Since video support its likely to appear in the near future (0.7 release), I'm planning to transition to a new backend for multimedia processing, the GStreamer backend will probably be left there for some time before dropping it completely.

### Candidates:
 * [MLT framework](https://www.mltframework.org/) used by kdenlive, openshot, and others. It appears to be more stable and without gobject and gobject-introspection it make our life easier ~~and the application potentially more portable on other platforms~~. **But** python 3 is not supported by the provided building scripts.

If someone have some options or suggestion on the argument,  I'd like to hear them :robot:

**Comment by mitscherdinger** [comment]
Ever looked into pipewire (https://github.com/PipeWire/pipewire)?

**Comment by FrancescoCeruti** [comment]
@mitscherdinger yeah, I know about it's existence, but it's only an API to handle audio and video sources, GStreamer it's in the middle, it does encoding, decoding and provide several plugins to manipulate the stream (like effects).

Ideally we could use it to output or to capture input for other devices, but all the processing still need to be implemented using some library like libav/ffmpeg and AFIK they lacks of a proper Python port.

Anyway thanks for the suggestion :)

**Comment by FrancescoCeruti** [comment]
So, since I didn't find any valid candidate, and I don't have time nor will to deal with this, I'll colse the issue, anyway the current (and future) architecture allow to replace quite easily the backend with a new implementation.

**Comment by mitscherdinger** [comment]
A bit late… MLT does list python(, again?) as a language binding. It also claims portability to Linux, BSD, Mac OS X MacPorts, Windows MinGW.
I was always searching for a video-player to work with LinuxShowPlayer as a "extension" to the internal features. Reading http://www.linux-magazine.com/Issues/2018/206/Command-Line-Melt made me wish someone with far more skills in programming as I do would make a linux based ShowPlayer with audio/video based on MLT/melt… Sounds really promising to me.

**Comment by FrancescoCeruti** [comment]
Hi @mitscherdinger! Apparently they now support python3 :-) at this point could take a look into it, and, if it's promising, I'll start to put something together.
Keep in mind that GStreamer is perfectly capable to handle video streams.
