### ISSUE TITLE
Crash when running audio cue with JACK (JACK inputs don't appear in cue edit dialog)

### ISSUE THREAD

**Issue by chadwellak** [FrancescoCeruti/linux-show-player#87]
The title pretty much says it all. I use JACK for almost everything and am accustomed to seeing the client app provide ports in QJackCtl. LiSP doesn't show any (though it does produce a MIDI port) and, like the title says, JACK inputs don't appear in the cue edit dialog.

Perhaps I'm missing a runtime library?

I'm using the AppImage, running on Fedora 25

Thanks for any thoughts. I'm very excited to get this up and running.

**Comment by chadwellak** [comment]
to add, this is a tidbit of the debug info:

> python3: ../common/JackPortType.cpp:49: const Jack::JackPortType* Jack::GetPortType(jack_port_type_id_t): Assertion `type_id >= 0 && type_id <= PORT_TYPES_MAX' failed.
> Fatal Python error: Aborted

Also, I noticed that after I start LiSP JACK slowly cranks out xruns, whether idle or not. 
Again, thanks for any thoughts. If I can provide anything please let me know.

**Comment by chadwellak** [comment]
After building it myself all is well. Sweet!!

**Comment by FrancescoCeruti** [comment]
Hi,
glad to see you have found a workaround, I fear it might be related to the AppImage bundle.

When possible I'll investigate the problem, thanks the report :)

**Comment by chadwellak** [comment]
Thanks so much for getting back. Yes, I did manage to get it running smoothly with jack but now unfortunately editing midi cues crashes it. It's strange, every other kind of cue can be edited but a second try (always the second try) to open the dialog for midi cues aborts the process.

I'm new to python and find it pretty confusing building packages but I also don't give up easily. Would you think that a library might be missing? I feel like I've checked everything.

In any case, this is a much appreciated effort that is long overdue. Thank you!

**Comment by FrancescoCeruti** [comment]
mmh, strange, can you run it as `linux-show-player -l debug` and post the output here?

**Comment by chadwellak** [comment]
Sure, and now that I'm looking reading back farther than I have previously I'm seeing that the OLA module is missing. I built it last night but I'm not sure how it links.  Here's the output:

> 14:34:55.825 INFO:: Using en_US locale
> 14:34:55.876 DEBUG:: MODULES: Loaded "Presets"
> 14:34:55.893 DEBUG:: MODULES: Loaded "Midi"
> 14:34:55.926 DEBUG:: MODULES: Loaded "ReplayGain"
> 14:34:55.966 DEBUG:: MODULES: Loaded "MediaInfo"
> 14:34:55.967 DEBUG:: ACTION-CUES: Loaded "VolumeControl"
> 14:34:55.968 DEBUG:: ACTION-CUES: Loaded "MidiCue"
> 14:34:55.968 DEBUG:: ACTION-CUES: Loaded "SeekCue"
> 14:34:55.969 DEBUG:: ACTION-CUES: Loaded "CommandCue"
> 14:34:55.969 DEBUG:: ACTION-CUES: Loaded "IndexActionCue"
> 14:34:55.970 DEBUG:: ACTION-CUES: Loaded "StopAll"
> 14:34:55.971 DEBUG:: ACTION-CUES: Loaded "CollectionCue"
> 14:34:55.971 DEBUG:: MODULES: Loaded "ActionCues"
> 14:34:55.972 DEBUG:: MODULES: Loaded "UriChanger"
> 14:34:55.992 INFO:: REMOTE: Session started at ('0.0.0.0', 8070)
> 14:34:55.992 DEBUG:: MODULES: Loaded "Remote"
> 14:34:56.123 DEBUG:: MODULES: Loaded "GstBackend"
> 14:34:56.124 DEBUG:: MODULES: Loaded "MediaCueMenus"
> 14:34:56.125 WARNING:: Cannot load module: timecode
> 14:34:56.125 DEBUG:: Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/lisp/plugins/timecode/__init__.py", line 22, in <module>
>     import ola
> ImportError: No module named 'ola'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/lisp/core/loading.py", line 92, in load
>     module = import_module(mod_path)
>   File "/usr/lib/python3.5/site-packages/lisp/core/loading.py", line 125, in import_module
>     return __import__(module_path, globals(), locals(), ['*'])
>   File "/usr/lib/python3.5/site-packages/lisp/plugins/timecode/__init__.py", line 25, in <module>
>     raise ImportError('OLA module not found, plugin not loaded.')
> ImportError: OLA module not found, plugin not loaded.
> 
> 14:34:56.126 DEBUG:: PLUGINS: Loaded "Synchronizer"
> 14:34:56.128 DEBUG:: PLUGINS: Loaded "Triggers"
> 14:34:56.133 DEBUG:: PLUGINS: Loaded "Controller"
> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
> 14:38:45.655 DEBUG:: PLUGINS: Initialized "Triggers"
> 14:38:45.655 DEBUG:: PLUGINS: Initialized "Controller"
> 14:38:45.655 DEBUG:: PLUGINS: Initialized "Synchronizer"
> 14:38:45.746 INFO:: Last action: AddItemAction
> 14:38:45.787 INFO:: Last action: AddItemAction
> 14:38:45.792 INFO:: Last action: AddItemAction
> 14:38:45.793 INFO:: Last action: AddItemAction
> 14:38:45.794 INFO:: Last action: AddItemAction
> 14:38:45.795 INFO:: Last action: AddItemAction
> 14:38:45.795 INFO:: Last action: AddItemAction
> 14:38:45.796 INFO:: Last action: AddItemAction
> 14:38:45.797 INFO:: Last action: AddItemAction
> 14:38:45.811 INFO:: Last action: AddItemAction
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/lisp/layouts/list_layout/layout.py", line 296, in double_clicked
>     self.edit_cue(cue)
>   File "/usr/lib/python3.5/site-packages/lisp/layouts/cue_layout.py", line 100, in edit_cue
>     edit_ui = CueSettings(cue, parent=MainWindow())
>   File "/usr/lib/python3.5/site-packages/lisp/ui/settings/cue_settings.py", line 89, in __init__
>     settings_widget.load_settings(cue_properties)
>   File "/usr/lib/python3.5/site-packages/lisp/modules/action_cues/midi_cue.py", line 152, in load_settings
>     dict_msg = str_msg_to_dict(str_msg)
>   File "/usr/lib/python3.5/site-packages/lisp/modules/midi/midi_utils.py", line 29, in str_msg_to_dict
>     for name in message._spec.arguments:
> AttributeError: 'Message' object has no attribute '_spec'
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/lisp/layouts/list_layout/layout.py", line 296, in double_clicked
>     self.edit_cue(cue)
>   File "/usr/lib/python3.5/site-packages/lisp/layouts/cue_layout.py", line 100, in edit_cue
>     edit_ui = CueSettings(cue, parent=MainWindow())
>   File "/usr/lib/python3.5/site-packages/lisp/ui/settings/cue_settings.py", line 89, in __init__
>     settings_widget.load_settings(cue_properties)
>   File "/usr/lib/python3.5/site-packages/lisp/modules/action_cues/midi_cue.py", line 152, in load_settings
>     dict_msg = str_msg_to_dict(str_msg)
>   File "/usr/lib/python3.5/site-packages/lisp/modules/midi/midi_utils.py", line 29, in str_msg_to_dict
>     for name in message._spec.arguments:
> AttributeError: 'Message' object has no attribute '_spec'
> Fatal Python error: Aborted
> 
> Thread 0x00007fa6d4bfa700 (most recent call first):
>   File "/usr/lib64/python3.5/threading.py", line 293 in wait
>   File "/usr/lib64/python3.5/queue.py", line 164 in get
>   File "/usr/lib64/python3.5/concurrent/futures/thread.py", line 64 in _worker
>   File "/usr/lib64/python3.5/threading.py", line 862 in run
>   File "/usr/lib64/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/usr/lib64/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007fa6d7f50700 (most recent call first):
>   File "/usr/lib/python3.5/site-packages/lisp/modules/remote/discovery.py", line 45 in run
>   File "/usr/lib64/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/usr/lib64/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007fa6d8751700 (most recent call first):
>   File "/usr/lib64/python3.5/selectors.py", line 376 in select
>   File "/usr/lib64/python3.5/socketserver.py", line 232 in serve_forever
>   File "/usr/lib/python3.5/site-packages/lisp/modules/remote/controller.py", line 69 in start
>   File "/usr/lib64/python3.5/threading.py", line 862 in run
>   File "/usr/lib64/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/usr/lib64/python3.5/threading.py", line 882 in _bootstrap
> 
> Current thread 0x00007fa713cd9700 (most recent call first):
>   File "/usr/lib/python3.5/site-packages/lisp/main.py", line 121 in main
>   File "/usr/bin/linux-show-player", line 5 in <module>
> Aborted (core dumped)

**Comment by chadwellak** [comment]
Hold on, hold on. I was using an .lsp file created with the appimage package. If I create a new session it appears to allow me to edit midi cues with no issues.

**Comment by FrancescoCeruti** [comment]
shouldn't happen, did you have the old file? can you send it and new one? maybe I can figure out why is this happening ...

**Comment by chadwellak** [comment]
Ok, this issue still happens even with new files. I can reliably duplicate it:

1. create a MIDI cue
2. edit the MIDI cue
3. cue works fine
4. select to edit, nothing happens
5. select to edit a second time, LiSP crashes (with the previously posted debug info)

This only happens with my built version to make JACK functional (and is probably my fault). This behavior doesn't occur with the AppImage.

**Comment by FrancescoCeruti** [comment]
Okay, so, I've an idea on what might cause the problem ...

Try to run `pip show mido` and if the "Version" is higher the 1.1.x (it's probably 1.2.8) then run `pip install -I mido==1.1.24`, if you want to install it in a user directory (no sudo) add `--user` to the last command.

This should install and older version of the midi library that, form the log, seems to be the problem, I'm probably using some functionality that as been dropped in newer versions :(

Let me know if the problem it's solved

**Comment by chadwellak** [comment]
Well, I did. It appears to make all MIDI functionality disappear. So I rebuilt it but still no love.
By disappear I mean that even in preferences there's no midi setting option. Trying to open a file with a MIDI cue drops and error:

> Cue not available or badly registered: MidiCue

**Comment by chadwellak** [comment]
Also, I can't help but point out that the AppImage file, with the exception of the whole JACK issued that I started this thread with, seems to work flawlessly.

**Comment by FrancescoCeruti** [comment]
mmh, okay, to install back the newer version of use `pip upgrade mido`, I can try to figure out the problems with JACK ...

Now that I've the possibility I'm going to test myself in a VM, and see if I can identify the problem

**Comment by aroomthedoomed** [comment]
hi
I have a similar issue. 

`
linux-show-player -l debug
22:11:31.354 INFO:: Using en_US locale
22:11:31.649 DEBUG:: MODULES: Loaded "GstBackend"
22:11:31.693 DEBUG:: MODULES: Loaded "MediaInfo"
22:11:31.694 DEBUG:: MODULES: Loaded "MediaCueMenus"
22:11:31.721 INFO:: REMOTE: Session started at ('0.0.0.0', 8070)
22:11:31.721 DEBUG:: MODULES: Loaded "Remote"
22:11:31.727 DEBUG:: MODULES: Loaded "Presets"
22:11:31.750 DEBUG:: MODULES: Loaded "Midi"
22:11:31.754 DEBUG:: MODULES: Loaded "ReplayGain"
22:11:31.759 DEBUG:: ACTION-CUES: Loaded "CollectionCue"
22:11:31.761 DEBUG:: ACTION-CUES: Loaded "CommandCue"
22:11:31.762 DEBUG:: ACTION-CUES: Loaded "SeekCue"
22:11:31.764 DEBUG:: ACTION-CUES: Loaded "VolumeControl"
22:11:31.765 DEBUG:: ACTION-CUES: Loaded "IndexActionCue"
22:11:31.766 DEBUG:: ACTION-CUES: Loaded "MidiCue"
22:11:31.769 DEBUG:: ACTION-CUES: Loaded "StopAll"
22:11:31.769 DEBUG:: MODULES: Loaded "ActionCues"
22:11:31.772 DEBUG:: MODULES: Loaded "UriChanger"
22:11:31.773 WARNING:: Cannot load module: timecode
22:11:31.774 DEBUG:: Traceback (most recent call last):
  File "/home/mekol/.local/lib/python3.5/site-packages/lisp/plugins/timecode/__init__.py", line 22, in <module>
    import ola
ImportError: No module named 'ola'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mekol/.local/lib/python3.5/site-packages/lisp/core/loading.py", line 92, in load
    module = import_module(mod_path)
  File "/home/mekol/.local/lib/python3.5/site-packages/lisp/core/loading.py", line 125, in import_module
    return __import__(module_path, globals(), locals(), ['*'])
  File "/home/mekol/.local/lib/python3.5/site-packages/lisp/plugins/timecode/__init__.py", line 25, in <module>
    raise ImportError('OLA module not found, plugin not loaded.')
ImportError: OLA module not found, plugin not loaded.

22:11:31.777 DEBUG:: PLUGINS: Loaded "Synchronizer"
22:11:31.792 DEBUG:: PLUGINS: Loaded "Controller"
22:11:31.795 DEBUG:: PLUGINS: Loaded "Triggers"
22:11:40.554 DEBUG:: PLUGINS: Initialized "Triggers"
22:11:40.556 DEBUG:: PLUGINS: Initialized "Synchronizer"
22:11:40.557 DEBUG:: PLUGINS: Initialized "Controller"
22:11:40.561 INFO:: Last action: AddItemAction
22:11:40.564 INFO:: Last action: AddItemAction
22:11:40.566 INFO:: Last action: AddItemAction
22:11:40.568 INFO:: Last action: AddItemAction
22:11:40.569 INFO:: Last action: AddItemAction
22:11:40.571 INFO:: Last action: AddItemAction
22:11:40.573 INFO:: Last action: AddItemAction
`

In cart layout mode, when I right click to edit a MIDI cue:

`
Traceback (most recent call last):
  File "/home/mekol/.local/lib/python3.5/site-packages/lisp/layouts/cart_layout/layout.py", line 400, in _edit_cue_action
    self.edit_cue(self.get_context_cue())
  File "/home/mekol/.local/lib/python3.5/site-packages/lisp/layouts/cue_layout.py", line 100, in edit_cue
    edit_ui = CueSettings(cue, parent=MainWindow())
  File "/home/mekol/.local/lib/python3.5/site-packages/lisp/ui/settings/cue_settings.py", line 89, in __init__
    settings_widget.load_settings(cue_properties)
  File "/home/mekol/.local/lib/python3.5/site-packages/lisp/modules/action_cues/midi_cue.py", line 152, in load_settings
    dict_msg = str_msg_to_dict(str_msg)
  File "/home/mekol/.local/lib/python3.5/site-packages/lisp/modules/midi/midi_utils.py", line 29, in str_msg_to_dict
    for name in message._spec.arguments:
AttributeError: 'Message' object has no attribute '_spec'
`


when trying to edit a MIDI cue, the version build by hand doesn't crash, the app image does. but nothing happen, can't edit any MIDI cue, more than once.

**Comment by FrancescoCeruti** [comment]
Mmmh, okay, I'll see what I can do

**Comment by wayneward** [comment]
Im the same need jack support but on my arch install i cant see jack outputs in the list is there a use flag i have to use for that ...

**Comment by FrancescoCeruti** [comment]
I've tested the AppImage on my Arch-Linux and jack seems working, except the edit-dialog may crash if I try to re-edit a jack-enabled cue after the first try, but I'm already fixing this problem.
I've also tested it in a Ubuntu 16.04 VM, it's working but, when using Unity, it drops "many" XRUN, this doesn't happen with a lighter DE, but it's working in a VM, with with limited resources.

@wayneward the LiSP ports are enabled (visible in QJackCtl) only when something is playing, you need to edit the connections into the cue settings

**Comment by wayneward** [comment]
Sussed it python-jack package 😎
