### ISSUE TITLE
Cue behaviors are not saved and description/note display

### ISSUE THREAD

**Issue by MarleyThompson** [FrancescoCeruti/linux-show-player#88]
Been looking for some Linux software like this for ages!
Especially like the cart layout with individual volume sliders. No one else seems to do this (for any OS).
Wanted to use this on an upcoming theater show but my first try brings up a few immediate problems:

In cart mode (which is the only mode I have used so far):
Cue behaviors are not saved.
Example Start action "Start" or "Fade in start" always shows "Fade in start" when restored from file.

Layout settings are not saved.
Example countdown mode not ticked, show volume ticked. These revert to default when restored from file.
For a complex performance, having to set all these each time would be a chore.
When restored from file needs to come back exactly as saved!

Other things that would be nice:
Description/Note text displayed on the cue. So notes for the operator visible on screen.
Ability to route the audio to various sinks selected by cue.

Apart from that - very good work! I am looking forward to version 0.6

**Comment by FrancescoCeruti** [comment]
Hi,

thank for the reporting the Cue behavior issues, I've look into it, should only happen that when you set "Start" or "Stop" it reset to a "Fade" version, this shouldn't be a big problem unless you want to be able to explicitly fade the cue in some places but don't want the "Fadein Start" or "Fadeout Start" as a default behavior (e.g. when you manually click on the button). In simple words if you have a zero seconds fadein/fadeout you shouldn't have big problems.

The layout settings you see in the menu are not saved, but you can change the application default in the applications settings (File > Preferences). With the next versions those check-boxes values will be saved in the show file. 

The notes are shown when you move the mouse over the cue, but with touchscreen it's useless, I'll try to figure out a way to make the notes visible on the cart layout.

Let me know if something it's unclear :)
