### ISSUE TITLE
Pages in Cart Mode

### ISSUE THREAD

**Issue by MarleyThompson** [FrancescoCeruti/linux-show-player#89]
Was hoping to organize my production in pages. Will be good when pages can be named eg: "Scene 1", "Scene 2", etc.

Problem:
So I created about 8 media cues in page1 (was not full obviously). Then created page 2 and created a new media cue there. But this new cue appears in page 1 not page 2! Presumably because page 1 is not full.

Explanation:
My current production has about 50 media cues (mixture of sound effects (SFX) and music cues (MQ) so to be able to organize into sections would be really nice.

BTW: Currently using Mulitplay (on Windows) This has a cue list very similar to your list mode. Will play with this mode on LiSP now. The reason I wanted to investigate the Cart mode is that it allows me to start, stop and adjust the volume of multiple playing cues simultaneously. Often I will be playing some background sounds, the actor enters and I need to start some music, for example at exactly the right time. Then, say some SFX on top of both after that!

Hope you don't mind me testing in a real use situation!

**Comment by FrancescoCeruti** [comment]
> Hope you don't mind me testing in a real use situation!

The opposite, I personally don't use the cart-layout in shows anymore, so it's good to have a real-usage feedback.

The ability to rename pages is already planned for the 0.6 version, the cue created always in the first "available" page is indeed a problem, I'll fix that too :)

> The reason I wanted to investigate the Cart mode is that it allows me to start, stop and adjust the volume of multiple playing cues simultaneously. Often I will be playing some background sounds, the actor enters and I need to start some music, for example at exactly the right time. Then, say some SFX on top of both after that!

You should be able to automate a lot of this using `Triggers` or using other cues for example the `Collection` or `Volume Control` cues (see the documentation for more info about those)

**Comment by MarleyThompson** [comment]
Used the Cart mode in a rehearsal yesterday - just to try it out - and is very usable and I am happy! The most important reason I use the Cart mode is that allows me to individually change the volume on a single cue when I have multiple cues playing. I don't think I can do that in List mode.

One simple thing:
Can the tab of the active page look different from the other pages? Either by text colour or by colouring the backgrounds differently.

More complicated things:
It would be nice if the cues in a cart page could be moved (dragged) around, so the view could be changed. In fact, snapping them to a hidden grid like icons on a desktop would be nice. Copying and pasting cues between pages - even better. There would have to be an "edit" mode and a"play" mode so that things would not get accidentally changed by the operator during a performance. Sorry, realize this is getting very ambitions now! 

Keep up the good work!

**Comment by FrancescoCeruti** [comment]
> Can the tab of the active page look different from the other pages? Either by text colour or by colouring the backgrounds differently.

Good suggestion

> It would be nice if the cues in a cart page could be moved (dragged) around, so the view could be changed. In fact, snapping them to a hidden grid like icons on a desktop would be nice. Copying and pasting cues between pages - even better.

Already there, see the docs:
http://linux-show-player-users.readthedocs.io/en/latest/cart_layout.html#move-and-copy-cues

> There would have to be an "edit" mode and a"play" mode so that things would not get accidentally changed by the operator during a performance. 

this is already been request, I'll keep the suggestion but right now it's not a priority

> Sorry, realize this is getting very ambitions now!

Eheh, no problem, any suggestion is apreciated

**Comment by FrancescoCeruti** [comment]
The various improvements on the tabs are now implemented in the development version.
here a preview of what they looks like:

![tabs_in_0 6](https://user-images.githubusercontent.com/5596673/41397815-a5d78bce-6fb5-11e8-9e8f-22289d9b5f74.png)

I'll close this, but let me know what do you think :)

**Comment by MarleyThompson** [comment]
Thank you very much. I have another production coming up next month. I look forward to using LiSP again!
