### ISSUE TITLE
Waveforms for search slider

### ISSUE THREAD

**Issue by fnetX** [FrancescoCeruti/linux-show-player#91]
One thing I miss here is a waveform to get an overview over the sound files. 
With waveforms I can see the drops in advance and navigate there if I there is need. 

I think the best way would be to analyze the files in advance and store the cached waveforms somehow within the project file to save performance on stage.

**Comment by FrancescoCeruti** [comment]
I've tried to implement this in the past, with a good share of problems, mostly related to performance issues.

It's something I'd love to include at some point, @offtools was also working on it, at some point, but I don't know what he have achieved

**Comment by fralix** [comment]
because of the performance I mentioned to analyze that in advance to reduce the system load during performance. 
It would a feature I would really appreciate.

**Comment by FrancescoCeruti** [comment]
Yes, that was something I was doing, now it was some time ago and I don't remember perfectly :thinking:

**Comment by fralix** [comment]
hmm ... alright ... but it would be really great as this is exactly what I need to consider this software as great instead of good ;-)

**Comment by nodiscc** [comment]
FYI quodlibet (python) contributors have implemented a [waveform seekbar plugin](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/events/waveformseekbar.py) that works quite well. All changes to this file including the first commit can be found in the [blame](https://github.com/quodlibet/quodlibet/blame/bead7e3d8cbcb0f2a2868f07cecf6a6f8439035f/quodlibet/quodlibet/ext/events/waveformseekbar.py). @FrancescoCeruti I don't know if this could help you and if the performance is up to par (ql is really good by the way), good luck :)

**Comment by FrancescoCeruti** [comment]
@nodiscc thanks, I've looked into it, the method they use is good until you need a low number of samples, which can be the case of a "small" seekbar, but I'd like to allow other components to use the same data, for example to set start/end of the track, in those situation you'll need an higher resolution especially for long tracks.

**Comment by FrancescoCeruti** [comment]
Okay, I've dedicated some time to this, I've a good method to get the waveform, sooner or later (more likely) you will see it implemented :)
