### ISSUE TITLE
About -> contributors

### ISSUE THREAD

**Issue by trebmuh** [FrancescoCeruti/linux-show-player#92]
When going to About -> contributors, we can see the contributors. In the translators section, we can see a name/nick + a link which is already great.

I'm suggesting here to add the language next to the translators' name. As the French translator of LiSP, I'd like the French users  to be able to reach me if they find a typo/error/... and for that, they need to know that I'm the current responsible/maintainer of the French translation.

**Comment by FrancescoCeruti** [comment]
Okay, good suggestion :)

**Comment by FrancescoCeruti** [comment]
This as been added in the development version, closing.

**Comment by trebmuh** [comment]
Super nice!
Thanks @FrancescoCeruti :+1:
