### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by trebmuh** [FrancescoCeruti/linux-show-player#93]
Running LiSP in French, I can see that there are some strings missing for translation.

![capture du 2017-12-31 15-30-39](https://user-images.githubusercontent.com/8705846/34462253-f1ec9808-ee3f-11e7-96a3-cba00b1f071f.png)
("Actions cues" and "Media cues")

![capture du 2017-12-31 15-41-05](https://user-images.githubusercontent.com/8705846/34462320-642a275e-ee41-11e7-89d1-f56bed876058.png)
("Cart Layout" and "List Layout")

I've been looking in the FR translation files and didn't see those strings so I guess there are not marked as "translatable" in the sources. Just a guess though.

**Comment by FrancescoCeruti** [comment]
> I've been looking in the FR translation files and didn't see those strings so I guess there are not marked as "translatable" in the sources. Just a guess though.

Yes, those string are not (yet) translated by the application, mainly because are used as keys in some place, this need to be changed.
