### ISSUE TITLE
application failed to start because it could not find or load the Qt platform plugin "xcb" in "".

### ISSUE THREAD

**Issue by AlCan13** [FrancescoCeruti/linux-show-player#97]
Good day,

I have tried to use AppImage on LiSP v0.5 of Debian 8 and 9 right after installation of minimalistic system based on LXDE.

getting same error when attempting to execute Linux_Show_Player-v0.5-1-x86_64.AppImage bu user or by root

```
Linux compaq-6910p-linux 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux

alexey@compaq-6910p-linux:~/Downloads$ ./Linux_Show_Player-v0.5-1-x86_64.AppImage 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted
alexey@compaq-6910p-linux:~/Downloads$ 
```
Could you advise on what to check and how to fix this 

are there any way to troubleshoot this?

cheers,
Alexey

**Comment by FrancescoCeruti** [comment]
Hi, can you launch it with `QT_DEBUG_PLUGINS=1 ./Linux_Show_Player-v0.5-1-x86_64.AppImage` and post here the output?

**Comment by fmiser** [comment]
I'm not the OP - but found this post as it matches my latest problem. Debian 8 (Jessie), 64 bit.

Here is the output I get from the debug command.

user@host:~/$ QT_DEBUG_PLUGINS=1 ./Linux_Show_Player-v0.5-1-x86_64.AppImage 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.so"
Found metadata in lib /tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.so, metadata=
{
    "IID": "org.qt-project.Qt.QIconEngineFactoryInterface",
    "MetaData": {
        "Keys": [
            "svg",
            "svgz",
            "svg.gz"
        ]
    },
    "className": "QSvgIconPlugin",
    "debug": false,
    "version": 329473
}


Got keys from plugin meta data ("svg", "svgz", "svg.gz")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so"
Found metadata in lib /tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 329473
}


Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqlinuxfb.so"
Found metadata in lib /tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 329473
}


Got keys from plugin meta data ("linuxfb")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.so"
Found metadata in lib /tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 329473
}


Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimalegl.so"
Found metadata in lib /tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 329473
}


Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.so"
Found metadata in lib /tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 329473
}


Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so"
Found metadata in lib /tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 329473
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_Linux_g8mNdE/usr/bin/platforms" ...
Cannot load library /tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_Linux_g8mNdE/usr/lib/x86_64-linux-gnu/libmirclient.so.9))
QLibraryPrivate::loadPlugin failed on "/tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_Linux_g8mNdE/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_Linux_g8mNdE/usr/lib/x86_64-linux-gnu/libmirclient.so.9))"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted

**Comment by FrancescoCeruti** [comment]
Thanks @fmiser, with Debian 8, the problem as outlined in #100, is that the AppImage has been build on Ubuntu 16.04, which have newer system libs, specifically, the libstdc++6 version is the problem here.

I know Debian 8 is reported as tested, my bad, since I've rebuild the AppImage without proper testing.

I'll see what can be done.

**Comment by AlCan13** [comment]
I have finally had time install Debian 9 on another miniPC and test again.
Downloaded Appimage and it worked ... but failed in another way - I will open(join to) a separate issue.

alexey@foxconn-linux:~/LiSP$ ls -al
total 254492
drwxr-xr-x  2 alexey alexey      4096 Feb  7 20:36 .
drwxr-xr-x 24 alexey alexey      4096 Feb  7 20:36 ..
-rwxr--r--  1 alexey alexey 260586864 Feb  7 20:34 LinuxShowPlayer-v0.5.1-x86_64.AppImage
alexey@foxconn-linux:~/LiSP$ ./LinuxShowPlayer-v0.5.1-x86_64.AppImage 
Create new configuration file: /home/alexey/.linux_show_player/config.cfg

(gst-plugin-scanner:1954): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstpango.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstpango.so: undefined symbol: gst_video_time_code_to_string




And now with DEBUG ON

alexey@foxconn-linux:~/LiSP$ 

alexey@foxconn-linux:~/LiSP$ QT_DEBUG_PLUGINS=1 ./Linux_Show_Player-v0.5-1-x86_64.AppImage
bash: ./Linux_Show_Player-v0.5-1-x86_64.AppImage: No such file or directory
alexey@foxconn-linux:~/LiSP$ QT_DEBUG_PLUGINS=1 ./LinuxShowPlayer-v0.5-1-x86_64.AppImage
bash: ./LinuxShowPlayer-v0.5-1-x86_64.AppImage: No such file or directory
alexey@foxconn-linux:~/LiSP$ QT_DEBUG_PLUGINS=1 ./LinuxShowPlayer-v0.5.1-x86_64.AppImage 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.so, metadata=
{
    "IID": "org.qt-project.Qt.QIconEngineFactoryInterface",
    "MetaData": {
        "Keys": [
            "svg",
            "svgz",
            "svg.gz"
        ]
    },
    "className": "QSvgIconPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("svg", "svgz", "svg.gz")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqlinuxfb.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("linuxfb")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimalegl.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqvnc.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/bin/platforms" ...
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so"
loaded library "Xcursor"
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/xcbglintegrations" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/xcbglintegrations/libqxcb-egl-integration.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/xcbglintegrations/libqxcb-egl-integration.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.Xcb.QXcbGlIntegrationFactoryInterface.5.5",
    "MetaData": {
        "Keys": [
            "xcb_egl"
        ]
    },
    "className": "QXcbEglIntegrationPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("xcb_egl")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/xcbglintegrations/libqxcb-glx-integration.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/xcbglintegrations/libqxcb-glx-integration.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.Xcb.QXcbGlIntegrationFactoryInterface.5.5",
    "MetaData": {
        "Keys": [
            "xcb_glx"
        ]
    },
    "className": "QXcbGlxIntegrationPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("xcb_glx")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/bin/xcbglintegrations" ...
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/xcbglintegrations/libqxcb-glx-integration.so"
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platformthemes" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platformthemes/libqgtk3.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platformthemes/libqgtk3.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "gtk3"
        ]
    },
    "className": "QGtk3ThemePlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("gtk3")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/bin/platformthemes" ...
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platformthemes/libqgtk3.so"
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforminputcontexts" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so, metadata=
{
    "IID": "org.qt-project.Qt.QPlatformInputContextFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "compose",
            "xim"
        ]
    },
    "className": "QComposePlatformInputContextPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("compose", "xim")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so, metadata=
{
    "IID": "org.qt-project.Qt.QPlatformInputContextFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "ibus"
        ]
    },
    "className": "QIbusPlatformInputContextPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("ibus")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/bin/platforminputcontexts" ...
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so"
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/styles" ...
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/bin/styles" ...
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqgif.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqgif.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "gif"
        ],
        "MimeTypes": [
            "image/gif"
        ]
    },
    "className": "QGifPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("gif")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqicns.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqicns.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "icns"
        ],
        "MimeTypes": [
            "image/x-icns"
        ]
    },
    "className": "QICNSPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("icns")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqico.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqico.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "ico",
            "cur"
        ],
        "MimeTypes": [
            "image/vnd.microsoft.icon"
        ]
    },
    "className": "QICOPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("ico", "cur")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqjpeg.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqjpeg.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "jpg",
            "jpeg"
        ],
        "MimeTypes": [
            "image/jpeg",
            "image/jpeg"
        ]
    },
    "className": "QJpegPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("jpg", "jpeg")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "svg",
            "svgz"
        ],
        "MimeTypes": [
            "image/svg+xml",
            "image/svg+xml-compressed"
        ]
    },
    "className": "QSvgPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("svg", "svgz")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtga.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtga.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "tga"
        ],
        "MimeTypes": [
            "image/x-tga"
        ]
    },
    "className": "QTgaPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("tga")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "tiff",
            "tif"
        ],
        "MimeTypes": [
            "image/tiff",
            "image/tiff"
        ]
    },
    "className": "QTiffPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("tiff", "tif")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwbmp.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwbmp.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "wbmp"
        ],
        "MimeTypes": [
            "image/vnd.wap.wbmp"
        ]
    },
    "className": "QWbmpPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("wbmp")
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwebp.so"
Found metadata in lib /tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwebp.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "webp"
        ],
        "MimeTypes": [
            "image/webp"
        ]
    },
    "className": "QWebpPlugin",
    "debug": false,
    "version": 330240
}


Got keys from plugin meta data ("webp")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/bin/imageformats" ...
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqgif.so"
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqicns.so"
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqico.so"
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqjpeg.so"
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.so"
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtga.so"
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.so"
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwbmp.so"
loaded library "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwebp.so"
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/lib/python3.5/site-packages/PyQt5/Qt/plugins/accessible" ...
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_LinuxSCQpUw2/usr/bin/accessible" ...

**Comment by AlCan13** [comment]
Strange ...
When I loaded it second time right after the first one above, it worked without any error messages.

and host info

Linux foxconn-linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

**Comment by AlCan13** [comment]
I would still prefer .deb package.

Just IMHO.

**Comment by FrancescoCeruti** [comment]
Mmh, strange ... the first one it's just a warning, it's pretty normal with the AppImage, did the application crash?

The `QT_DEBUG_PLUGINS` it's a QT specific variable, for LiSP debug output you need to use `-- log debug` as a launch option

**Comment by FrancescoCeruti** [comment]
About the .deb package, I'm playing around with the openSUSE "Open Build Service", so I'm might be able to provide them :)
