### ISSUE TITLE
CRASH when edit a cue midi for twice

### ISSUE THREAD

**Issue by toonix76** [FrancescoCeruti/linux-show-player#98]
App crash when i edit a cue midi for the second time, in both mode cart and list, even if i 've saved the session between two editions;
Ubuntu 16.04.03 64b

**Comment by FrancescoCeruti** [comment]
@toonix76 Thank, I'm already aware of the issue, I'll look into it asap.

@aroomthedoomed it's okay, the other issue was opened for a problem with JACK, better to track the MIDI issues here, to avoid confusion.

**Comment by FrancescoCeruti** [comment]
Fixed in the last release
